{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Date\",\"Dim Doctor\",\"Dim Facility\",\"Dim Service Category\",\"Fact Visit Budget\",\"Fact Budget\",\"Fact Visit\",\"Fact WTNK Visit\",\"Fact Voucher\",\"Last Refresh Date\",\"Dim Specialty\",\"Calculations\",\"Dim Business Line\",\"Environment Name\",\"Dim Customer Account\",\"QA_CON\",\"PRD_CON\",\"DEV_CON\",\"DEV_CATALOG\",\"QA_CATALOG\",\"PRD_CATALOG\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Environment Name",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"development\" meta [IsParameterQuery=true, List={\"development\", \"production\", \"qa\"}, DefaultValue=\"development\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "8159d960-e350-40bb-b8b3-ca948b969034"
      },
      {
        "name": "QA_CON",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"adb-874297882712675.15.azuredatabricks.net\" meta [IsParameterQuery=true, List={\"adb-874297882712675.15.azuredatabricks.net#(lf)\"}, DefaultValue=\"adb-874297882712675.15.azuredatabricks.net#(lf)\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "7cb502cf-ae26-425c-842c-f8ead7904879"
      },
      {
        "name": "PRD_CON",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"adb-845583881941178.18.azuredatabricks.net\" meta [IsParameterQuery=true, List={\"adb-845583881941178.18.azuredatabricks.net#(lf)\"}, DefaultValue=\"adb-845583881941178.18.azuredatabricks.net#(lf)\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "f841b4a9-8d75-466f-99c5-fe7ab97bf669"
      },
      {
        "name": "DEV_CON",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"adb-4340824508160044.4.azuredatabricks.net\" meta [IsParameterQuery=true, List={\"adb-4340824508160044.4.azuredatabricks.net#(lf)\"}, DefaultValue=\"adb-4340824508160044.4.azuredatabricks.net#(lf)\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "18e6536a-3c53-43f3-aeaa-bcbb05b5e3c2"
      },
      {
        "name": "DEV_CATALOG",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"sql/protocolv1/o/4340824508160044/1015-130713-e1771g2p\" meta [IsParameterQuery=true, List={\"sql/protocolv1/o/4340824508160044/1015-130713-e1771g2p\"}, DefaultValue=\"sql/protocolv1/o/4340824508160044/1015-130713-e1771g2p\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "644c212e-1d02-4934-b543-c1c4dc90b63e"
      },
      {
        "name": "QA_CATALOG",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"sql/protocolv1/o/874297882712675/0206-102452-pv3weizg\" meta [IsParameterQuery=true, List={\"sql/protocolv1/o/874297882712675/0206-102452-pv3weizg#(lf)\"}, DefaultValue=\"sql/protocolv1/o/874297882712675/0206-102452-pv3weizg#(lf)\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "51c7a877-f8bd-4bab-b51d-b49b128ba6fe"
      },
      {
        "name": "PRD_CATALOG",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"sql/protocolv1/o/845583881941178/0204-153521-a5gg6a6y\" meta [IsParameterQuery=true, List={\"sql/protocolv1/o/845583881941178/0204-153521-a5gg6a6y#(lf)\"}, DefaultValue=\"sql/protocolv1/o/845583881941178/0204-153521-a5gg6a6y#(lf)\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "04b8550b-63de-4ccf-aafb-ffe41dda81cc"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Fact Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Dim Tables"
      }
    ],
    "relationships": [
      {
        "name": "88cae530-ddd7-8d75-b8e6-59ccf3f86e10",
        "fromColumn": "FK Specialty",
        "fromTable": "Fact Voucher",
        "toColumn": "PK Specialty",
        "toTable": "Dim Specialty"
      },
      {
        "name": "e97e5e5e-bbb6-1c0a-1480-9f95953768a0",
        "fromColumn": "FK Facility",
        "fromTable": "Fact Voucher",
        "toColumn": "PK Facility",
        "toTable": "Dim Facility"
      },
      {
        "name": "2fbf84bd-fdfb-279c-984c-95c1ce253779",
        "fromColumn": "FK DATE",
        "fromTable": "Fact Voucher",
        "toColumn": "PK DATE",
        "toTable": "Date"
      },
      {
        "name": "ff670b61-ea55-6918-5ab7-2190050ca129",
        "fromColumn": "FK Business Line",
        "fromTable": "Fact Voucher",
        "toColumn": "PK Business Line",
        "toTable": "Dim Business Line"
      },
      {
        "name": "6064005c-e4db-fc7e-1970-a949a09f1bf3",
        "fromColumn": "FK Facility",
        "fromTable": "Fact Visit",
        "toColumn": "PK Facility",
        "toTable": "Dim Facility"
      },
      {
        "name": "af77f4bf-470e-02dc-b982-8814ebb868b4",
        "fromColumn": "FK DATE",
        "fromTable": "Fact Visit",
        "toColumn": "PK DATE",
        "toTable": "Date"
      },
      {
        "name": "f2a90772-e913-f9ec-afcc-a5c552f3ac7f",
        "fromColumn": "FK Specialty",
        "fromTable": "Fact Visit",
        "toColumn": "PK Specialty",
        "toTable": "Dim Specialty"
      },
      {
        "name": "681822d4-b259-53ba-f2b4-8f3151300715",
        "fromColumn": "FK Service Category",
        "fromTable": "Fact Visit",
        "toColumn": "PK Service Category",
        "toTable": "Dim Service Category"
      },
      {
        "name": "55c225b7-7105-dc64-5800-d9372ca8a3b3",
        "fromColumn": "FK Facility",
        "fromTable": "Fact Visit Budget",
        "toColumn": "PK Facility",
        "toTable": "Dim Facility"
      },
      {
        "name": "5ae0efcc-91df-516d-b12c-14e3375c8c00",
        "fromColumn": "Fk Business Line",
        "fromTable": "Fact Visit Budget",
        "toColumn": "PK Business Line",
        "toTable": "Dim Business Line"
      },
      {
        "name": "37efe1ca-4635-7e48-b17c-efc1f0884de6",
        "fromColumn": "FK DATE",
        "fromTable": "Fact Visit Budget",
        "toColumn": "PK DATE",
        "toTable": "Date"
      },
      {
        "name": "26479246-1e18-7619-a9ac-5c7310937cb7",
        "fromColumn": "FK Specialty",
        "fromTable": "Fact Visit Budget",
        "toColumn": "PK Specialty",
        "toTable": "Dim Specialty"
      },
      {
        "name": "79b5f41f-d9c8-b330-bf41-413ae47f5219",
        "fromColumn": "Fk Business Line",
        "fromTable": "Fact Budget",
        "toColumn": "PK Business Line",
        "toTable": "Dim Business Line"
      },
      {
        "name": "fc682d0b-c98d-53e2-12b7-06712e42dc9f",
        "fromColumn": "Fk Specialty",
        "fromTable": "Fact Budget",
        "toColumn": "PK Specialty",
        "toTable": "Dim Specialty"
      },
      {
        "name": "85a55492-1331-159e-cd0b-a8be8af150ec",
        "fromColumn": "Fk Date",
        "fromTable": "Fact Budget",
        "toColumn": "PK DATE",
        "toTable": "Date"
      },
      {
        "name": "9f2a1da0-f2fa-9c30-a5cc-5644ebbbc6ac",
        "fromColumn": "Fk Facility",
        "fromTable": "Fact Budget",
        "toColumn": "PK Facility",
        "toTable": "Dim Facility"
      },
      {
        "name": "AutoDetected_329d2c7c-1bda-4767-a735-4fa44f01eede",
        "fromColumn": "FK DATE",
        "fromTable": "Fact WTNK Visit",
        "toColumn": "PK DATE",
        "toTable": "Date"
      },
      {
        "name": "AutoDetected_17c66aab-b678-4851-9a2c-cce7af3818e3",
        "fromColumn": "FK Facility",
        "fromTable": "Fact WTNK Visit",
        "toColumn": "PK Facility",
        "toTable": "Dim Facility"
      },
      {
        "name": "AutoDetected_07e4acc4-0c85-4e61-ba3e-31e516298d9f",
        "fromColumn": "FK Specialty",
        "fromTable": "Fact WTNK Visit",
        "toColumn": "PK Specialty",
        "toTable": "Dim Specialty"
      },
      {
        "name": "AutoDetected_240644f7-25b1-4729-b318-db4f3db2328d",
        "fromColumn": "FK Doctor",
        "fromTable": "Fact Voucher",
        "toColumn": "PK Doctor",
        "toTable": "Dim Doctor"
      },
      {
        "name": "AutoDetected_4bacb3ec-5995-4b7c-9292-3381f11423d1",
        "fromColumn": "FK Doctor",
        "fromTable": "Fact Visit",
        "toColumn": "PK Doctor",
        "toTable": "Dim Doctor"
      },
      {
        "name": "AutoDetected_cb2665a4-31d5-4381-a7c6-7a539b4948d4",
        "fromColumn": "FK Doctor ID",
        "fromTable": "Fact Visit Budget",
        "toColumn": "PK Doctor",
        "toTable": "Dim Doctor"
      },
      {
        "name": "AutoDetected_50834262-9d64-4958-8d7e-23515eb7773f",
        "fromColumn": "Fk Doctor ID",
        "fromTable": "Fact Budget",
        "toColumn": "PK Doctor",
        "toTable": "Dim Doctor"
      },
      {
        "name": "AutoDetected_8f2290b8-64b9-45d1-9232-c8a84cab0ef0",
        "fromColumn": "FK Doctor",
        "fromTable": "Fact WTNK Visit",
        "toColumn": "PK Doctor",
        "toTable": "Dim Doctor"
      },
      {
        "name": "AutoDetected_2620557e-35e4-4460-a5c0-6394d6354577",
        "fromColumn": "FK Business Line",
        "fromTable": "Fact WTNK Visit",
        "toColumn": "PK Business Line",
        "toTable": "Dim Business Line"
      },
      {
        "name": "AutoDetected_9977f84c-6404-41fb-a000-c736552cf869",
        "fromColumn": "FK Business Line",
        "fromTable": "Fact Visit",
        "toColumn": "PK Business Line",
        "toTable": "Dim Business Line"
      },
      {
        "name": "4ad15663-9879-9436-b98b-e7086b57829d",
        "fromColumn": "FK Customer Account",
        "fromTable": "Fact Visit",
        "toColumn": "PK Customer Account",
        "toTable": "Dim Customer Account"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PK DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78d04ebe-6b04-4011-932d-2a96df5d761a",
            "sourceColumn": "PK DATE",
            "summarizeBy": "none"
          },
          {
            "name": "BK DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "2c88dfa5-ff17-4451-badc-2f3d6fa38f49",
            "sourceColumn": "BK DATE",
            "summarizeBy": "none"
          },
          {
            "name": "YEAR WEEK NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "252c8826-fe90-4ccb-9d5a-ee86be04afcb",
            "sourceColumn": "YEAR WEEK NR",
            "summarizeBy": "none"
          },
          {
            "name": "YEAR WEEK CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e826e76c-ef94-4f74-a998-2061c7d6c415",
            "sourceColumn": "YEAR WEEK CODE",
            "summarizeBy": "none"
          },
          {
            "name": "YEAR NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80e1bcdb-5aa7-46f8-8f47-b70b0958fef6",
            "sourceColumn": "YEAR NR",
            "summarizeBy": "sum"
          },
          {
            "name": "YEAR OF WEEK NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "901eaa58-56e2-474a-932a-0dd654319e00",
            "sourceColumn": "YEAR OF WEEK NR",
            "summarizeBy": "sum"
          },
          {
            "name": "SEMESTER NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da3269bc-68bc-46f7-9dc3-83c4b5d6084e",
            "sourceColumn": "SEMESTER NR",
            "summarizeBy": "sum"
          },
          {
            "name": "SEMESTER NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79cd2b84-9170-487f-aa95-70f5799a89e2",
            "sourceColumn": "SEMESTER NAME",
            "summarizeBy": "none"
          },
          {
            "name": "QUARTER NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d6875df-f791-470a-ad0b-7b39f9b83dce",
            "sourceColumn": "QUARTER NR",
            "summarizeBy": "sum"
          },
          {
            "name": "QUARTER NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73c92d3a-155f-4a4d-a51b-be530b1f4c8d",
            "sourceColumn": "QUARTER NAME",
            "summarizeBy": "none"
          },
          {
            "name": "MONTH NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3b9227c0-a280-455b-971e-2ec8909d60b7",
            "sourceColumn": "MONTH NR",
            "summarizeBy": "sum"
          },
          {
            "name": "MONTH NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "456a1ce3-e47e-49ee-b373-4d1ceddfeb2b",
            "sortByColumn": "MONTH NR",
            "sourceColumn": "MONTH NAME",
            "summarizeBy": "none"
          },
          {
            "name": "MONTH SHORT NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "83956de9-c61c-462e-9355-eedaa47ace5c",
            "sortByColumn": "MONTH NR",
            "sourceColumn": "MONTH SHORT NAME",
            "summarizeBy": "none"
          },
          {
            "name": "WEEK NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c37f52b-f5db-4d1f-a0fb-0613bda0c390",
            "sourceColumn": "WEEK NR",
            "summarizeBy": "sum"
          },
          {
            "name": "MONTH DAY NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2cd8773a-8686-461c-903e-5bfb0b93adce",
            "sourceColumn": "MONTH DAY NR",
            "summarizeBy": "sum"
          },
          {
            "name": "WEEK DAY NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ded8b3b-c827-4518-b1b1-21c935f6311b",
            "sourceColumn": "WEEK DAY NR",
            "summarizeBy": "sum"
          },
          {
            "name": "DAY NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a7e9fb6-cf67-4553-99a4-24faa3cca094",
            "sourceColumn": "DAY NR",
            "summarizeBy": "none"
          },
          {
            "name": "WEEK DAY SHORT NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e70b3543-c69e-429e-8369-1a707829cddf",
            "sourceColumn": "WEEK DAY SHORT NAME",
            "summarizeBy": "none"
          },
          {
            "name": "REPORTINGDAY FLG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9c1e75b4-761f-423d-9add-97a179fdf3b9",
            "sourceColumn": "REPORTINGDAY FLG",
            "summarizeBy": "sum"
          },
          {
            "name": "YEAR MONTH NR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70332b41-9199-4ab7-a9ac-c9065fd29f12",
            "sourceColumn": "YEAR MONTH NR",
            "summarizeBy": "none"
          },
          {
            "name": "YEAR MONTH CODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb092525-84ae-4826-8533-3e3be62f987b",
            "sortByColumn": "YEAR MONTH NR",
            "sourceColumn": "YEAR MONTH CODE",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "e44c4152-e8b6-4ab2-af2e-99525f273c8b",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "queryGroup": "Dim Tables",
            "source": {
              "expression": [
                "let",
                "    Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_d_date_View = gold_Schema{[Name=\"vw_d_date\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_d_date_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Doctor",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Doctor ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "768f4c10-ac1a-4ab3-b05c-96b6cf064755",
            "sourceColumn": "Doctor ID",
            "summarizeBy": "none"
          },
          {
            "name": "Doctor Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42e1e60c-fe75-4bba-b03d-d0942956477f",
            "sourceColumn": "Doctor Name",
            "summarizeBy": "none"
          },
          {
            "name": "PK Doctor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "823f86ac-79e4-4740-99d2-e29283bbced7",
            "sourceColumn": "PK Doctor",
            "summarizeBy": "none"
          },
          {
            "name": "Resource Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ce37eac-7499-4a17-9865-d7dccf6959f9",
            "sourceColumn": "Resource Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "91d53f61-8082-4538-81a2-40286f54fbf7",
        "partitions": [
          {
            "name": "Dim Doctor",
            "mode": "import",
            "queryGroup": "Dim Tables",
            "source": {
              "expression": [
                "let",
                "     Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON,DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_d_doctor_View = gold_Schema{[Name=\"vw_d_doctor\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_d_doctor_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Facility",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PK Facility",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c55d747-21de-44d4-bb88-db6bb66251d3",
            "sourceColumn": "PK Facility",
            "summarizeBy": "none"
          },
          {
            "name": "Facility Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8231174e-b76f-47f9-b51d-54ab98866589",
            "sourceColumn": "Facility Name",
            "summarizeBy": "none"
          },
          {
            "name": "Facility ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2090e0b6-ecfa-4a00-9c34-5aee9745d1aa",
            "sourceColumn": "Facility ID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "d8bd811b-36b3-4e07-9660-4a48cf398d6d",
        "partitions": [
          {
            "name": "Dim Facility",
            "mode": "import",
            "queryGroup": "Dim Tables",
            "source": {
              "expression": [
                "let",
                "     Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_d_facility_View = gold_Schema{[Name=\"vw_d_facility\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_d_facility_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Service Category",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PK Service Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db6c5b25-6fd9-4b9e-a570-8a6fd1b40378",
            "sourceColumn": "PK Service Category",
            "summarizeBy": "none"
          },
          {
            "name": "Service Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d14e13a-d05a-439c-81be-a48aac0551cb",
            "sourceColumn": "Service Code",
            "summarizeBy": "none"
          },
          {
            "name": "Service Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3890f594-6c9c-4607-8c15-660d47e7eb68",
            "sourceColumn": "Service Name",
            "summarizeBy": "none"
          },
          {
            "name": "L1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10d4971c-dbd9-4770-8d68-38df347ea6fd",
            "sourceColumn": "L1",
            "summarizeBy": "none"
          },
          {
            "name": "L2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d199625-e991-47f1-9916-eb1cb70c77b2",
            "sourceColumn": "L2",
            "summarizeBy": "none"
          },
          {
            "name": "L3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1037af4b-7197-4e4e-8ad5-f127d8503862",
            "sourceColumn": "L3",
            "summarizeBy": "none"
          },
          {
            "name": "L4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9050b713-e281-4409-8732-58bcd22088f1",
            "sourceColumn": "L4",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6168ea13-498c-4a1d-9e50-d6e90b2c0238",
        "partitions": [
          {
            "name": "Dim Service Category",
            "mode": "import",
            "queryGroup": "Dim Tables",
            "source": {
              "expression": [
                "let",
                "    Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_d_servicecategory_View = gold_Schema{[Name=\"vw_d_servicecategory\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_d_servicecategory_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Voucher",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dfdec1dd-f84f-47f4-9bcf-8a69f59f70c0",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Agreement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec03c09d-2d5d-46e8-b8bd-6837d7b28e24",
            "sourceColumn": "Agreement",
            "summarizeBy": "none"
          },
          {
            "name": "L1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0e239f9-7dcc-4a1f-af4b-3bfd762de64b",
            "sourceColumn": "L1",
            "summarizeBy": "none"
          },
          {
            "name": "L2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6916bde-e9b1-4994-ad75-82a0bb5f0dbb",
            "sourceColumn": "L2",
            "summarizeBy": "none"
          },
          {
            "name": "FK Facility",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3655ec71-c941-4548-8836-6e231ac43c82",
            "sourceColumn": "FK Facility",
            "summarizeBy": "none"
          },
          {
            "name": "FK Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "176ef98e-5ee8-4e0f-918a-d688b49527d0",
            "sourceColumn": "FK Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "FK Doctor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc1f2276-4b10-442e-945b-2dc124d46238",
            "sourceColumn": "FK Doctor",
            "summarizeBy": "none"
          },
          {
            "name": "Specialty Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a547d990-fabd-4ad8-ac48-938ae09dfc89",
            "sourceColumn": "Specialty Group",
            "summarizeBy": "none"
          },
          {
            "name": "Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c729db9-8d11-4761-8e0b-3fa215a698fc",
            "sourceColumn": "Flag",
            "summarizeBy": "none"
          },
          {
            "name": "FK DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64641a44-8b26-43d3-a326-9f3784dd206f",
            "sourceColumn": "FK DATE",
            "summarizeBy": "none"
          },
          {
            "name": "FK Business Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f21f42b-962e-4793-adde-c6c41ea7eb69",
            "sourceColumn": "FK Business Line",
            "summarizeBy": "none"
          },
          {
            "name": "Legal Entity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ac85ef0-cc1e-4fc3-bc94-32f707ba102a",
            "sourceColumn": "Legal Entity",
            "summarizeBy": "none"
          },
          {
            "name": "Journal Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2bd8403-154d-4621-8663-6554da95389d",
            "sourceColumn": "Journal Account ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90a8e7eb-e5aa-4238-a040-0244e74d9fab",
        "partitions": [
          {
            "name": "Fact Voucher",
            "mode": "import",
            "queryGroup": "Fact Tables",
            "source": {
              "expression": [
                "let",
                "     Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_f_voucher_View = gold_Schema{[Name=\"vw_f_voucher\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_f_voucher_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Last Refresh Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date Last Refreshed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy. h:nn:ss AM/PM ",
            "lineageTag": "8d8f11fe-ecf4-4d68-a5a4-e9e6e8f3772d",
            "sourceColumn": "Date Last Refreshed",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "582dc119-b834-40ef-b13e-1814b417dc5c",
        "partitions": [
          {
            "name": "Last Refresh Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #table(type table[Date Last Refreshed=datetime], {{DateTime.LocalNow()}})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Specialty",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PK Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "743d2db2-c596-468e-8e16-a1f5503e3696",
            "sourceColumn": "PK Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "Specialty ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b16a30e8-6cf4-43c6-b83c-6f47158afc2a",
            "sourceColumn": "Specialty ID",
            "summarizeBy": "count"
          },
          {
            "name": "Specialty Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b545b946-140d-49f2-b67b-b4a23601cccc",
            "sourceColumn": "Specialty Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "82e793c1-93b8-49c0-ac22-ea72fffa6f64",
        "partitions": [
          {
            "name": "Dim Specialty",
            "mode": "import",
            "queryGroup": "Dim Tables",
            "source": {
              "expression": [
                "let",
                "     Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_d_specialty_View = gold_Schema{[Name=\"vw_d_specialty\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_d_specialty_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calculations",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "86b1c0bc-98e4-4879-a74e-c92a8e2a5de5",
        "measures": [
          {
            "name": "SRC_$_Pharmacy Revenue",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "    var Revenue_Commission = CALCULATE(",
              "        SUM('Fact Voucher'[Amount]),",
              "        'Fact Voucher'[Journal Account ID] = \"315107\" )",
              "",
              "    var Pharmacies_Rent = CALCULATE(",
              "        SUM('Fact Voucher'[Amount]),",
              "        'Fact Voucher'[Journal Account ID] = \"330002\" )",
              "",
              "RETURN (Revenue_Commission+Pharmacies_Rent) * -1"
            ],
            "formatString": "0.0",
            "lineageTag": "49880b13-5f65-484a-8176-d4d2b0efa434"
          },
          {
            "name": "CurrentMonth EndDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Date Measures",
            "expression": [
              "",
              "VAR Selected_Month = MAX('Date'[BK DATE])",
              "VAR Current_Period = MAX('Last Refresh Date'[Date Last Refreshed])",
              "",
              "RETURN",
              "     if (",
              "        ISFILTERED('Date'),",
              "        DATE(",
              "        YEAR(Selected_Month),",
              "        MONTH(Selected_Month),",
              "        day(Selected_Month)",
              "        )",
              "        ,",
              "",
              "         DATE(",
              "            YEAR(Current_Period),",
              "            MONTH(Current_Period),",
              "            day(Current_Period)",
              "        )",
              "        )"
            ],
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "e4078108-86d6-4989-a11c-510ddc9c4d6d"
          },
          {
            "name": "CurrentMonth StartDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Date Measures",
            "expression": [
              "",
              "VAR Selected_Month = MIN('Date'[BK DATE])",
              "VAR Current_Period = MAX('Last Refresh Date'[Date Last Refreshed])",
              "RETURN",
              "    if (",
              "        ISFILTERED('Date'),",
              "        DATE(",
              "            YEAR(Selected_Month),",
              "            MONTH(Selected_Month),",
              "            01",
              "        )",
              "        ,",
              "        DATE(",
              "            YEAR(Current_Period),",
              "            MONTH(Current_Period),",
              "            01",
              "        )",
              ")",
              ""
            ],
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "e78667ba-23e5-4fa6-a203-1919b53297ac"
          },
          {
            "name": "Previous YTD EndDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Date Measures",
            "expression": [
              "",
              "VAR Selected_Month = ",
              "    IF(",
              "        MONTH(MAX('Date'[BK DATE])) = 2 && DAY(MAX('Date'[BK DATE])) = 29, ",
              "        DATE(YEAR(MAX('Date'[BK DATE])) - 1, 2, 28), ",
              "        DATE(YEAR(MAX('Date'[BK DATE])) - 1, MONTH(MAX('Date'[BK DATE])), DAY(MAX('Date'[BK DATE])))",
              "    )",
              "",
              "VAR Current_EndDate = MAX('Last Refresh Date'[Date Last Refreshed])",
              "",
              "RETURN ",
              "",
              "IF(",
              "    ISFILTERED('Date'),",
              "    DATE(",
              "        YEAR(Selected_Month),",
              "        MONTH(Selected_Month),",
              "        DAY(Selected_Month)",
              "    ),  ",
              "    DATE(",
              "        YEAR(Current_EndDate)-1,",
              "        MONTH(Current_EndDate),",
              "        DAY(Current_EndDate)",
              "    )",
              ")",
              "",
              ""
            ],
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "120ec4b3-5bae-4c85-bcbb-04ff00652f3e"
          },
          {
            "name": "Previous YTD StartDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Date Measures",
            "expression": [
              "",
              "VAR Selected_Month = MIN('Date'[BK DATE])",
              "VAR Current_Period = MAX('Last Refresh Date'[Date Last Refreshed])",
              "RETURN",
              "IF(",
              "    ISFILTERED('Date'),",
              "    DATE(",
              "        YEAR(Selected_Month)-1,",
              "        1,",
              "        1",
              "    ), ",
              "    DATE(",
              "        YEAR(Current_Period)-1,",
              "        1,",
              "        1",
              "    )",
              ")"
            ],
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "664f4f7a-888d-49cb-9b73-f7072d25a83e"
          },
          {
            "name": "$_Pharmacy Revenue PY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Month = [Previous YTD StartDate]",
              "VAR End_Month = [Previous YTD EndDate]",
              "VAR result = ",
              "    CALCULATE( [SRC_$_Pharmacy Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)",
              "RETURN",
              "    result",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "c231064b-1c1d-4238-98a7-8cf759eacdcd"
          },
          {
            "name": "$_Pharmacy Revenue CY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Pharmacy Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Pharmacy Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "3c9e6bd0-e2e0-4a1c-af2a-09b0e09ecd52"
          },
          {
            "name": "SRC_$_Bulk Deal Cash Revenue",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Cash = CALCULATE(",
              "    SUM('Fact Voucher'[Amount]),",
              "    'Fact Voucher'[Agreement] = \"001\"",
              "    ,'Fact Voucher'[L1] = \"Net Revenue\",",
              "    'Fact Voucher'[L2] = \"Revenue\"",
              "    ,FILTER('Dim Business Line','Dim Business Line'[Business Line] = \"Bulk Deal\")",
              ")",
              "",
              "RETURN",
              "-1*Cash ",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "6891a922-0d8f-4b62-97e2-1517760141db"
          },
          {
            "name": "SRC_$_COGS",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Direct_Materials =",
              "    CALCULATE (",
              "        SUM ( 'Fact Voucher'[Amount] ),",
              "        'Fact Voucher'[Flag] = \"Original\",",
              "        'Fact Voucher'[L1] = \"Direct Materials\",",
              "        'Fact Voucher'[L2] IN { \"Drugs And Consumables\", \"Services (Non Materials)\" },",
              "        NOT ( 'Fact Voucher'[Specialty Group] IN { \"Head Office\", \"Main Store\" } )",
              "    )",
              "VAR ManPower =",
              "    CALCULATE (",
              "        SUM ( 'Fact Voucher'[Amount] ),",
              "        'Fact Voucher'[Flag] = \"Original\",",
              "        'Fact Voucher'[L1] = \"Manpower Cost\",",
              "        'Fact Voucher'[L2]",
              "            IN { \"Salaries & Benefits\", \"Subscriptions and renewals\", \"Manpower Cost - Rev.\" },",
              "        NOT ( 'Fact Voucher'[Specialty Group] IN { \"Head Office\", \"Main Store\" } )",
              "    )",
              "VAR LabCost =",
              "    CALCULATE (",
              "        SUM ( 'Fact Voucher'[Amount] ),",
              "        'Fact Voucher'[Flag] = \"Original\",",
              "        'Fact Voucher'[L1] = \"Lab. Management Cost\",",
              "        'Fact Voucher'[L2] = \"Lab. Management Cost\",",
              "        NOT ( 'Fact Voucher'[Specialty Group] IN { \"Head Office\", \"Main Store\" } )",
              "    )",
              "VAR OtherDirectExpenses =",
              "    CALCULATE (",
              "        SUM ( 'Fact Voucher'[Amount] ),",
              "        'Fact Voucher'[Flag] = \"Original\",",
              "        'Fact Voucher'[L1] = \"Other Direct Expenses\",",
              "        'Fact Voucher'[L2]",
              "            IN {",
              "                \"Government Fees\",",
              "                \"Insurance\",",
              "                \"IT Expenses\",",
              "                \"Maintenance\",",
              "                \"Other Expenses\",",
              "                \"Professional Expenses\",",
              "                \"Rent\",",
              "                \"Utilities\"",
              "            },",
              "        NOT ( 'Fact Voucher'[Specialty Group] IN { \"Head Office\", \"Main Store\" } )",
              "    )",
              "VAR Exceptions =",
              "    CALCULATE (",
              "        SUM ( 'Fact Voucher'[Amount] ),",
              "        'Fact Voucher'[Flag] = \"Allocated To\",",
              "        'Fact Voucher'[L1] = \"Manpower Cost\",",
              "        'Fact Voucher'[L2] = \"Manpower Cost - Rev.\",",
              "        NOT ( 'Fact Voucher'[Specialty Group] IN { \"Head Office\", \"Main Store\" } )",
              "    )",
              "RETURN",
              "    Direct_Materials + ManPower + LabCost + OtherDirectExpenses + Exceptions",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "f4c3b599-7729-4e8b-9b5a-85ceb7b98b4b"
          },
          {
            "name": "SRC_$_G&A",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR ManPower =",
              "    CALCULATE (",
              "        SUM ( 'Fact Voucher'[Amount] ),",
              "        'Fact Voucher'[Flag] = \"Allocated To\",",
              "        'Fact Voucher'[L1] = \"Manpower Cost\",",
              "        'Fact Voucher'[L2] IN { \"Salaries & Benefits\", \"Subscriptions and renewals\" }",
              "    )",
              "VAR OtherExpenses =",
              "    CALCULATE (",
              "        SUM ( 'Fact Voucher'[Amount] ),",
              "        'Fact Voucher'[Flag] = \"Allocated To\",",
              "        'Fact Voucher'[L1] = \"Other Direct Expenses\",",
              "        'Fact Voucher'[L2]",
              "            IN {",
              "                \"Government Fees\",",
              "                \"Insurance\",",
              "                \"IT Expenses\",",
              "                \"Maintenance\",",
              "                \"Other Expenses\",",
              "                \"Professional Expenses\",",
              "                \"Rent\",",
              "                \"Utilities\"",
              "            }",
              "    )",
              "RETURN",
              "    ManPower + OtherExpenses",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "1273ecd6-0e08-4b84-a357-1abafd257309"
          },
          {
            "name": "SRC_$_Marketing",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "CALCULATE(SUM('Fact Voucher'[Amount])",
              ",'Fact Voucher'[L1] = \"Marketing\", 'Fact Voucher'[L2] = \"Marketing\"",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "2b93d367-6aa4-48c8-8327-f24dc792bcc7"
          },
          {
            "name": "SRC_$_Cash Revenue Without B2B",
            "displayFolder": "Visit",
            "expression": [
              "",
              "    CALCULATE(SUM('Fact Visit'[Amount]),",
              "    'Fact Visit'[Is Cash] = TRUE()",
              "    )",
              "    +[SRC_$_WTNK Cash Revenue]"
            ],
            "formatString": "0.0",
            "lineageTag": "0a87cb29-4627-41c7-8844-80f6fbd78c35"
          },
          {
            "name": "SRC_$_Credit Revenue",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR InvoiceBeforeVat = CALCULATE(SUM('Fact Visit'[Amount]),",
              "    'Fact Visit'[Is Cash] = FALSE()",
              ")",
              "VAR BilledAmount = CALCULATE(SUM('Fact Visit'[Rejection Amount]),",
              "    'Fact Visit'[Is Cash] = FALSE() , 'Fact Visit'[Payer Type] = \"Sponsor\"",
              ")",
              "RETURN InvoiceBeforeVat-BilledAmount+ [SRC_$_WTNK Credit Revenue]"
            ],
            "formatString": "0.0",
            "lineageTag": "2b387281-805c-4a3a-98d2-acf55a9af103"
          },
          {
            "name": "SRC_$_Net Revenue",
            "displayFolder": "Visit",
            "expression": "[SRC_$_Bulk Deal Cash Revenue]+[SRC_$_Cash Revenue Without B2B]+[SRC_$_Credit Revenue]+[SRC_$_Pharmacy Revenue]",
            "formatString": "0.0",
            "lineageTag": "61709c27-0fe4-49d5-a422-ff8804728898"
          },
          {
            "name": "SRC_$_Gross Profit",
            "displayFolder": "Voucher",
            "expression": "[SRC_$_Net Revenue] - [SRC_$_COGS]",
            "formatString": "0.0",
            "lineageTag": "96e84705-543b-4adc-82fa-a3d7ff43bfc5"
          },
          {
            "name": "SRC_$_EBIDTA",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "    [SRC_$_Gross Profit] - [SRC_$_G&A] - [SRC_$_Marketing]"
            ],
            "formatString": "0.0",
            "lineageTag": "d40fe705-1841-4883-8375-3a3f187b47f8"
          },
          {
            "name": "SRC_$_Other Revenue",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR OtherRevenue =",
              "    CALCULATE (",
              "        SUM ( 'Fact Voucher'[Amount] ),",
              "        'Fact Voucher'[L1] = \"Other Revenue\",",
              "        NOT ( 'Fact Voucher'[Specialty Group] IN { \"Head Office\", \"Main Store\" } ),",
              "        'Fact Voucher'[Flag] IN { \"Allocated To\", \"Original\" }",
              "    )",
              "RETURN",
              "    -1 * OtherRevenue",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "c77dcc48-89b4-4f23-99ff-4cfaeda9c644"
          },
          {
            "name": "SRC_$_Depreciation After Allocation",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'Fact Voucher'[Amount] ),",
              "    'Fact Voucher'[L1] = \"Depreciation Of Tangible Fixed Assets\",",
              "    NOT ( 'Fact Voucher'[Specialty Group] IN { \"Head Office\", \"Main Store\" } ),",
              "    'Fact Voucher'[Flag] IN { \"Allocated To\", \"Original\" }",
              ")",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "94c5b859-17d5-4208-91b2-7d8407e183c8"
          },
          {
            "name": "SRC_$_Depreciation Before Allocation",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'Fact Voucher'[Amount] ),",
              "    'Fact Voucher'[L1] = \"Depreciation Of Tangible Fixed Assets\",",
              "    NOT ( 'Fact Voucher'[Specialty Group] IN { \"Head Office\", \"Main Store\" } ),",
              "    'Fact Voucher'[Flag] = \"Original\"",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "5a9fd01f-ae69-47c6-9750-e242f3a286e0"
          },
          {
            "name": "SRC_$_Interest Exp",
            "displayFolder": "Voucher",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact Voucher'[Amount]),",
              "    'Fact Voucher'[L1] = \"Interest Exp.\",NOT('Fact Voucher'[Specialty Group] in {\"Head Office\", \"Main Store\"}), 'Fact Voucher'[Flag] in  {\"Allocated To\", \"Original\"}",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "9eec8ade-6c4a-4c80-ac76-ed0ba58af3f6"
          },
          {
            "name": "SRC_$_Zakat & Emergency Expenses",
            "displayFolder": "Voucher",
            "expression": [
              "CALCULATE(",
              "      SUM('Fact Voucher'[Amount]),",
              "    'Fact Voucher'[L1] = \"Zakat & Emergency Expenses\",NOT('Fact Voucher'[Specialty Group] in {\"Head Office\", \"Main Store\"}), 'Fact Voucher'[Flag] in  {\"Allocated To\", \"Original\"}",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "c651817f-1458-4ad1-bd67-ecd717f742b0"
          },
          {
            "name": "SRC_$_Net Profit",
            "displayFolder": "Voucher",
            "expression": "[SRC_$_EBIDTA] +[SRC_$_Other Revenue] - ([SRC_$_Depreciation After Allocation]+[SRC_$_Interest Exp]+[SRC_$_Zakat & Emergency Expenses])",
            "formatString": "0.0",
            "lineageTag": "e0c9bda2-2711-441a-8aa1-6e3944572296"
          },
          {
            "name": "SRC_$_Cash Revenue with B2B",
            "displayFolder": "Visit",
            "expression": [
              "",
              "",
              "[SRC_$_Cash Revenue Without B2B] +[SRC_$_Bulk Deal Cash Revenue]"
            ],
            "formatString": "0.0",
            "lineageTag": "a53a9628-0d7d-44e3-8cb9-969dd9c85fb0"
          },
          {
            "name": "SRC_$_Operating Profit",
            "displayFolder": "Voucher",
            "expression": "[SRC_$_Gross Profit] -[SRC_$_Depreciation Before Allocation]-[SRC_$_Marketing]",
            "formatString": "0.0",
            "lineageTag": "c1f82d02-5a63-4c65-b053-d792cb3335ce"
          },
          {
            "name": "SRC_%_Gross Profit Margin",
            "displayFolder": "Voucher",
            "expression": "DIVIDE([SRC_$_Gross Profit],[SRC_$_Net Revenue],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1070c835-565f-468e-a077-f97b1a24643f"
          },
          {
            "name": "SRC_%_EBIDTA Margin",
            "displayFolder": "Voucher",
            "expression": "DIVIDE([SRC_$_EBIDTA],[SRC_$_Net Revenue],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9412faf9-eb8b-4ef9-b7af-a94805649abf"
          },
          {
            "name": "SRC_%_Operating Profit Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "DIVIDE ( [SRC_$_Operating Profit], [SRC_$_Net Revenue], 0 )",
              ""
            ],
            "lineageTag": "267771f4-60f2-440e-af2f-63a0ea960c93"
          },
          {
            "name": "$_Cash Revenue Without B2B CY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Cash Revenue Without B2B],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Cash Revenue Without B2B],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "d9f6761a-79b9-4d2e-a199-2cacc3f208c5"
          },
          {
            "name": "$_Credit Revenue CY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Credit Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Credit Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "ade86b07-080d-4909-9331-d190f4e190f0"
          },
          {
            "name": "$_Net Revenue CY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Net Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Net Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "27de6976-6740-4d8a-8020-58a0bbebf315"
          },
          {
            "name": "$_Operating Profit CY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Operating Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Operating Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "a31ede19-3f04-4e8d-8318-5e7878c34be0"
          },
          {
            "name": "$_EBIDTA CY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_EBIDTA],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_EBIDTA],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "1f0506a3-039b-471c-ac98-1c17fb076b4b"
          },
          {
            "name": "$_Gross Profit CY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Gross Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Gross Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "a159ca14-452b-492b-b897-12b61b23113d"
          },
          {
            "name": "$_Net Profit CY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Net Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Net Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "2164282a-7449-401d-90a1-ce0c622dd48e"
          },
          {
            "name": "%_Operating Profit Margin CY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_%_Operating Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Operating Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "05da254b-1b45-4bce-a090-65d7e2ef5693"
          },
          {
            "name": "SRC_%_Net Profit Margin",
            "displayFolder": "Voucher",
            "expression": "DIVIDE([SRC_$_Net Profit],[SRC_$_Net Revenue],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9fdc4b07-7611-488f-bcab-e88b0b1abe0e"
          },
          {
            "name": "%_Net Profit Margin CY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_%_Net Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Net Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              "",
              "",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f0fb7527-9d44-4ec5-837f-bda833608bc1"
          },
          {
            "name": "%_EBIDTA Margin CY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_%_EBIDTA Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_EBIDTA Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              "",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f717e76e-ebbc-496b-9385-784e8e6fc0b3"
          },
          {
            "name": "%_Gross Profit Margin CY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_%_Gross Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Gross Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6cf7161d-50b4-4797-af6d-b66733d8b594"
          },
          {
            "name": "$_EBIDTA PY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_$_EBIDTA],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_EBIDTA],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "f265f103-291c-4f32-b301-91a804019b41"
          },
          {
            "name": "$_Gross Profit PY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_$_Gross Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Gross Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "4b12a2cb-79bd-44db-8b40-ff06036ef2a4"
          },
          {
            "name": "$_Net Profit PY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_$_Net Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Net Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "6366c2ca-0ea0-408a-a02e-5ff0c6aca26d"
          },
          {
            "name": "$_Operating Profit PY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_$_Operating Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Operating Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "8b406a07-2105-4e62-bb3d-5d3da8a72a51"
          },
          {
            "name": "$_Credit Revenue PY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_$_Credit Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Credit Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "d1b9139e-4fbc-42a9-94b1-54b64bd2b5f5"
          },
          {
            "name": "$_Cash Revenue Without B2B PY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_$_Cash Revenue Without B2B],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Cash Revenue Without B2B],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              "",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "52859c88-ec91-4441-a198-16eab9dad4e4"
          },
          {
            "name": "$_Net Revenue PY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_$_Net Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Net Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )"
            ],
            "formatString": "0.0",
            "lineageTag": "d5c20bc6-3424-42ee-b17a-3c484a992e0e"
          },
          {
            "name": "%_EBIDTA Margin PY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_%_EBIDTA Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_EBIDTA Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              "",
              "",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a244b5d3-2577-4385-bc28-a0a6d7c5722c"
          },
          {
            "name": "%_Gross Profit Margin PY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_%_Gross Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Gross Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              "",
              "",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "42711285-a4e2-4bc1-948e-f7757e205ccf"
          },
          {
            "name": "%_Net Profit Margin PY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_%_Net Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Net Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              "",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7cee4787-d9de-4633-80c3-45aca9d5314c"
          },
          {
            "name": "%_Operating Profit Margin PY",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_%_Operating Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Operating Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              "",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "8f76d854-e886-43bd-8091-2adfd922e945"
          },
          {
            "name": "SRC_Cash Visits",
            "displayFolder": "Visit",
            "expression": [
              "",
              "var Cash= ",
              "CALCULATE(",
              "    DISTINCTCOUNT('Fact Visit'[Transaction ID]),",
              "    'Fact Visit'[Is Visit] = TRUE(),'Fact Visit'[Is Cash] = TRUE(), 'Dim Business Line'[Business Line] <> \"Home Care\"",
              ")",
              "    ",
              "var  Homevisit=",
              "CALCULATE(",
              "    SUMX(",
              "        SUMMARIZE(",
              "            'Fact Visit',",
              "            'Fact Visit'[Patient ID],",
              "            'Date'[BK DATE]",
              "        ),",
              "        1  ",
              "    ),",
              "    'Dim Business Line'[Facility Clinic] = \"Home Visit\", 'Fact Visit'[Is Visit] = TRUE(),'Fact Visit'[Is Cash] = TRUE()",
              ")",
              "",
              "var  HomeCare=",
              "CALCULATE(",
              "    SUMX(",
              "        SUMMARIZE(",
              "            'Fact Visit',",
              "            'Fact Visit'[Patient ID],",
              "            'Date'[YEAR MONTH NR]",
              "        ),",
              "        1  ",
              "    ),",
              "    'Dim Business Line'[Facility Clinic] = \"Home Care\", 'Fact Visit'[Is Visit] = TRUE(),'Fact Visit'[Is Cash] = TRUE()",
              ")",
              "RETURN homevisit + [SRC_WTNK Cash Visits] + HomeCare + Cash"
            ],
            "formatString": "0",
            "lineageTag": "112d8f3f-2eab-430c-aef6-f63c0d80bb06"
          },
          {
            "name": "SRC_Credit Visits",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Credit = ",
              "CALCULATE(DISTINCTCOUNT('Fact Visit'[Transaction ID]),",
              "    'Fact Visit'[Is Visit] = TRUE(),'Fact Visit'[Is Cash] = FALSE(), 'Dim Business Line'[Business Line] <> \"Home Care\"",
              " )",
              "        ",
              "var  Homevisit=",
              "CALCULATE(",
              "    SUMX(",
              "        SUMMARIZE(",
              "            'Fact Visit',",
              "            'Fact Visit'[Patient ID],",
              "            'Date'[BK DATE]",
              "        ),",
              "        1  ",
              "    ),",
              "    'Dim Business Line'[Facility Clinic] = \"Home Visit\", 'Fact Visit'[Is Visit] = TRUE(),'Fact Visit'[Is Cash] = FALSE()",
              ")",
              "",
              "var  HomeCare=",
              "CALCULATE(",
              "    SUMX(",
              "        SUMMARIZE(",
              "            'Fact Visit',",
              "            'Fact Visit'[Patient ID],",
              "            'Date'[YEAR MONTH NR]",
              "        ),",
              "        1  ",
              "    ),",
              "    'Dim Business Line'[Facility Clinic] = \"Home Care\", 'Fact Visit'[Is Visit] = TRUE(),'Fact Visit'[Is Cash] = FALSE()",
              ")",
              "RETURN homevisit + [SRC_WTNK Credit Visits] + HomeCare +Credit"
            ],
            "formatString": "0",
            "lineageTag": "a8d292a2-b56f-4084-a19b-79e55a9f0c72"
          },
          {
            "name": "SRC_Total Visits",
            "displayFolder": "Visit",
            "expression": "[SRC_Cash Visits] + [SRC_Credit Visits]",
            "formatString": "0",
            "lineageTag": "a804eb48-02ff-453c-a739-756cd912643c"
          },
          {
            "name": "SRC_$_Cash Revenue Per Visit",
            "displayFolder": "Visit",
            "expression": "DIVIDE([SRC_$_Cash Revenue Without B2B],[SRC_Cash Visits],0)",
            "formatString": "0.0",
            "lineageTag": "8f367f2c-a6b3-4b2f-acc7-3efa2dcbcd24"
          },
          {
            "name": "SRC_$_Credit Revenue Per Visit",
            "displayFolder": "Visit",
            "expression": "DIVIDE([SRC_$_Credit Revenue],[SRC_Credit Visits],0)",
            "formatString": "0.0",
            "lineageTag": "1d8876d9-a38a-49d2-ba75-9073169c83e6"
          },
          {
            "name": "SRC_Budget Cash Visits",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit Budget",
            "expression": "SUM('Fact Visit Budget'[Cash Visits Number])",
            "lineageTag": "6795fa32-4edc-4f5a-8dba-062c0c7e052b"
          },
          {
            "name": "SRC_Budget Credit Visits",
            "displayFolder": "Visit Budget",
            "expression": [
              "SUM('Fact Visit Budget'[Credit Visits Number])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bfa5c3ac-41ec-44d6-a5e1-fcb9e6240fe2"
          },
          {
            "name": "SRC_Budget Total Visits",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit Budget",
            "expression": "[SRC_Budget Cash Visits] +[SRC_Budget Credit Visits]",
            "lineageTag": "a33cbb94-b3ff-4647-b99f-52b52f61d218"
          },
          {
            "name": "SRC_$_Budget Cash Revenue",
            "displayFolder": "Visit Budget",
            "expression": [
              "",
              "SUM('Fact Visit Budget'[Cash Revenue])"
            ],
            "formatString": "0.0",
            "lineageTag": "74dbbef2-c23c-43a2-b612-d54c5339c357"
          },
          {
            "name": "SRC_$_Budget Credit Revenue",
            "displayFolder": "Visit Budget",
            "expression": [
              "",
              "SUM('Fact Visit Budget'[Net Credit Revenue])"
            ],
            "formatString": "0.0",
            "lineageTag": "428e0b5b-55a1-42f4-b428-ac9d1953e8a9"
          },
          {
            "name": "SRC_$_Budget Cash Revenue Per Visit",
            "displayFolder": "Visit Budget",
            "expression": "DIVIDE([SRC_$_Budget Cash Revenue],[SRC_Budget Cash Visits],0)",
            "formatString": "0.0",
            "lineageTag": "83151a73-d178-47d9-a761-233c3f4562d5"
          },
          {
            "name": "SRC_$_Budget Credit Revenue Per Visit",
            "displayFolder": "Visit Budget",
            "expression": "DIVIDE([SRC_$_Budget Credit Revenue],[SRC_Budget Credit Visits],0)",
            "formatString": "0.0",
            "lineageTag": "09c185ea-ea55-4b36-bf07-227b9df8d878"
          },
          {
            "name": "SRC_$_Budget Pharmacy Revenue",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Profit = ",
              "    CALCULATE(",
              "        SUM('Fact Budget'[Amount]),",
              "        'Fact Budget'[Journal Account ID] = 330002",
              "    )",
              "VAR Rent =   ",
              "    CALCULATE(",
              "        SUM('Fact Budget'[Amount]),",
              "        'Fact Budget'[Journal Account ID] = 315107",
              "    )",
              "RETURN Rent + Profit"
            ],
            "formatString": "0.0",
            "lineageTag": "71f13c15-c147-4484-9c5b-eea96d58e045"
          },
          {
            "name": "SRC_$_Budget COGS",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Direct_Materials = CALCULATE(",
              "    SUM('Fact Budget'[Amount]),",
              "    'Fact Budget'[Allocated] = FALSE(), 'Fact Budget'[L1] = \"Direct Materials\", 'Fact Budget'[L2] in {\"Drugs And Consumables\", \"Services (Non Materials)\"}",
              ")",
              "VAR ManPower = CALCULATE(",
              "    SUM('Fact Budget'[Amount]),",
              "    'Fact Budget'[Allocated] = FALSE(), 'Fact Budget'[L1] = \"Manpower Cost\", 'Fact Budget'[L2] in {\"Salaries & Benefits\",\"Subscriptions and renewals\",\"Manpower Cost - Rev.\"}",
              ")",
              "VAR LabCost = CALCULATE(",
              "    SUM('Fact Budget'[Amount]),",
              "    'Fact Budget'[Allocated] = FALSE(), 'Fact Budget'[L1] = \"Lab. Management Cost\", 'Fact Budget'[L2] = \"Lab. Management Cost\"",
              ")",
              "VAR OtherDirectExpenses = CALCULATE(",
              "    SUM('Fact Budget'[Amount]),",
              "    'Fact Budget'[Allocated] = FALSE(), 'Fact Budget'[L1] = \"Other Direct Expenses\", 'Fact Budget'[L2] in {\"Government Fees\",\"Insurance\", \"IT Expenses\",\"Maintenance\", \"Other Expenses\",\"Professional Expenses\", \"Rent\", \"Utilities\"}",
              ")",
              "VAR Exceptions = CALCULATE(",
              "    SUM('Fact Budget'[Amount]),",
              "    'Fact Budget'[Allocated] = TRUE(), 'Fact Budget'[L1] = \"Manpower Cost\", 'Fact Budget'[L2]=\"Manpower Cost - Rev.\"",
              ")",
              "RETURN ",
              "    Direct_Materials + ManPower + LabCost +OtherDirectExpenses +Exceptions",
              "",
              "",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "a12b7c44-99a2-40b6-b932-77bcfba9d487"
          },
          {
            "name": "SRC_$_Budget G&A",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR ManPower =",
              "    CALCULATE (",
              "        SUM ( 'Fact Budget'[Amount] ),",
              "        'Fact Budget'[Allocated] = TRUE (),",
              "        'Fact Budget'[L1] = \"Manpower Cost\",",
              "        'Fact Budget'[L2] IN { \"Salaries & Benefits\", \"Subscriptions and renewals\" }",
              "    )",
              "VAR OtherExpenses =",
              "    CALCULATE (",
              "        SUM ( 'Fact Budget'[Amount] ),",
              "        'Fact Budget'[Allocated] = TRUE (),",
              "        'Fact Budget'[L1] = \"Other Direct Expenses\",",
              "        'Fact Budget'[L2]",
              "            IN {",
              "                \"Government Fees\",",
              "                \"Insurance\",",
              "                \"IT Expenses\",",
              "                \"Maintenance\",",
              "                \"Other Expenses\",",
              "                \"Professional Expenses\",",
              "                \"Rent\",",
              "                \"Utilities\"",
              "            }",
              "    )",
              "RETURN",
              "    ManPower + OtherExpenses"
            ],
            "formatString": "0.0",
            "lineageTag": "33809ab0-1cb7-457f-993e-3d927fd4f98a"
          },
          {
            "name": "SRC_$_Budget Marketing",
            "displayFolder": "Budget",
            "expression": [
              "",
              "CALCULATE(SUM('Fact Budget'[Amount])",
              ",'Fact Budget'[L1] = \"Marketing\", 'Fact Budget'[L2] = \"Marketing\"",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "81f66102-abfd-4dd3-8a73-f92d523db3b9"
          },
          {
            "name": "SRC_$_Budget Depreciation Before Allocation",
            "displayFolder": "Budget",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact Budget'[Amount]),'Fact Budget'[L1] = \"Depreciation Of Tangible Fixed Assets\", 'Fact Budget'[Allocated] = FALSE()",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "1075185a-f2ed-4ff8-8589-cef8517926fa"
          },
          {
            "name": "SRC_$_Budget Depreciation After Allocation",
            "displayFolder": "Budget",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact Budget'[Amount]),'Fact Budget'[L1] = \"Depreciation Of Tangible Fixed Assets\"",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "64622605-e567-4fdf-a39d-d648d773b888"
          },
          {
            "name": "SRC_$_Budget Other Revenue",
            "displayFolder": "Budget",
            "expression": [
              "",
              " CALCULATE(SUM('Fact Budget'[Amount]),",
              "    'Fact Budget'[L1] = \"Other Revenue\"",
              "    )"
            ],
            "formatString": "0.0",
            "lineageTag": "ee8ee7c6-5a07-4d1c-9ef2-c28ce6ce8c1a"
          },
          {
            "name": "SRC_$_Budget Zakat & Emergency Expenses",
            "displayFolder": "Budget",
            "expression": [
              "CALCULATE(",
              "      SUM('Fact Budget'[Amount]),",
              "    'Fact Budget'[L1] = \"Zakat & Emergency Expenses\"",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "26567a01-b69c-4420-aefb-d8b91f240571"
          },
          {
            "name": "SRC_$_Budget Interest Exp",
            "displayFolder": "Budget",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact Budget'[Amount]),",
              "    'Fact Budget'[L1] = \"Interest Exp.\"",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "bc0a4e07-9c06-4d5d-86ba-8c701fc7d3b1"
          },
          {
            "name": "SRC_$_Budget Net Revenue",
            "displayFolder": "Budget",
            "expression": "[SRC_$_Budget Cash Revenue]+[SRC_$_Budget Credit Revenue]+[SRC_$_Budget Pharmacy Revenue]",
            "formatString": "0.0",
            "lineageTag": "1af5c0ee-d101-4fd1-b3f6-ee7af8fa705f"
          },
          {
            "name": "SRC_$_Budget Gross Profit",
            "displayFolder": "Budget",
            "expression": "[SRC_$_Budget Net Revenue]-[SRC_$_Budget COGS]",
            "formatString": "0.0",
            "lineageTag": "36834928-11aa-4be4-ac27-59217e9b6edc"
          },
          {
            "name": "SRC_$_Budget EBIDTA",
            "displayFolder": "Budget",
            "expression": "[SRC_$_Budget Gross Profit]-[SRC_$_Budget G&A]-[SRC_$_Budget Marketing]",
            "formatString": "0.0",
            "lineageTag": "3b7e224c-4f75-491c-9f92-a3109e1f2268"
          },
          {
            "name": "SRC_$_Budget Operating Profit",
            "displayFolder": "Budget",
            "expression": "[SRC_$_Budget Gross Profit]-[SRC_$_Budget Depreciation Before Allocation]-[SRC_$_Budget Marketing]",
            "formatString": "0.0",
            "lineageTag": "44258606-bb93-4663-9711-1f3281f672e6"
          },
          {
            "name": "SRC_$_Budget Net Profit",
            "displayFolder": "Budget",
            "expression": "[SRC_$_Budget EBIDTA]+[SRC_$_Budget Other Revenue]-([SRC_$_Budget Zakat & Emergency Expenses]+[SRC_$_Budget Depreciation After Allocation]+[SRC_$_Budget Interest Exp])",
            "formatString": "0.0",
            "lineageTag": "09a74560-0214-4ce1-886d-6b5ade17d95d"
          },
          {
            "name": "SRC_%_Budget Net Profit Margin",
            "displayFolder": "Budget",
            "expression": "DIVIDE([SRC_$_Budget Net Profit],[SRC_$_Budget Net Revenue],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "98a7de0a-60b2-4a99-9480-fef31be8d9a0"
          },
          {
            "name": "SRC_%_Budget EBIDTA Margin",
            "displayFolder": "Budget",
            "expression": "DIVIDE([SRC_$_Budget EBIDTA],[SRC_$_Budget Net Revenue],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0f063fa4-c790-4964-b18c-7124681099a7"
          },
          {
            "name": "SRC_%_Budget Gross Profit Margin",
            "displayFolder": "Budget",
            "expression": "DIVIDE([SRC_$_Budget Gross Profit],[SRC_$_Budget Net Revenue],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3fac094f-4dba-4dd1-b1fe-c7214adaab19"
          },
          {
            "name": "SRC_%_Budget Operating Profit Margin",
            "displayFolder": "Budget",
            "expression": "DIVIDE([SRC_$_Budget Operating Profit],[SRC_$_Budget Net Revenue],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "30086003-2ec6-462e-a31b-cf50cba6177d"
          },
          {
            "name": "Credit Revenue Per Visit PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_$_Credit Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Credit Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "lineageTag": "05159ade-ccc7-45ff-b55b-9f22b2ae8eee"
          },
          {
            "name": "Cash Revenue Per Visit PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_$_Cash Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Cash Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "lineageTag": "3970ee58-6f76-481a-b222-ee0fbcef130f"
          },
          {
            "name": "Credit Visit PY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_Credit Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_Credit Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f7ecfbdc-e285-40d8-9978-2143f2b6e3ba"
          },
          {
            "name": "Cash Visit PY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_Cash Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_Cash Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4897c7d1-58aa-4007-a77c-8e6d3b83e0d2"
          },
          {
            "name": "Total Visit PY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Previous YTD StartDate]",
              "VAR End_Year = [Previous YTD EndDate]",
              "VAR Start_Month = [Previous Month StartDate]",
              "VAR End_Month = [Previous Month EndDate]",
              "VAR _YTD = ",
              "    CALCULATE( [SRC_Total Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year)",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_Total Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month)    ",
              "RETURN",
              "    SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bab6c99e-a09f-4bc5-b1e7-5bcee47592c8"
          },
          {
            "name": "Credit Revenue Per Visit CY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Credit Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Credit Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "lineageTag": "3353444d-f341-41df-b04d-b36fe3c098ed"
          },
          {
            "name": "Cash Revenue Per Visit CY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Cash Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Cash Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "lineageTag": "3cb3a1cc-b42e-411f-9053-42f33f7b79e1"
          },
          {
            "name": "Cash Visit CY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_Cash Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_Cash Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "61469cb3-3947-4ba3-992e-0e09b7385db6"
          },
          {
            "name": "Credit Visit CY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_Credit Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_Credit Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "828127a6-aae8-4943-a378-d556c148672f"
          },
          {
            "name": "Total Visit CY",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_Total Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_Total Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "6ade49a1-fceb-4462-9949-c8d6dc95d0f5"
          },
          {
            "name": "$_Budget Credit Revenue CY",
            "displayFolder": "Visit Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Budget Credit Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Budget Credit Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "39b8ef1d-6680-47d3-9194-afc78a813bec"
          },
          {
            "name": "$_Budget Cash Revenue CY",
            "displayFolder": "Visit Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Budget Cash Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Budget Cash Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "65e2a886-7d52-425a-9931-3a127dd3283d"
          },
          {
            "name": "$_Budget Credit Revenue Per Visit CY",
            "displayFolder": "Visit Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Budget Credit Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Budget Credit Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "90d53925-bbdc-4f01-bd3d-26b85065e815"
          },
          {
            "name": "$_Budget Cash Revenue Per Visit CY",
            "displayFolder": "Visit Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Budget Cash Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Budget Cash Revenue Per Visit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "    ",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "fbd9bf48-b993-417a-875e-65b783878318"
          },
          {
            "name": "Budget Credit Visit CY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Visit Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_Budget Credit Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_Budget Credit Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b84a576e-a389-44b0-a836-60a61465449d"
          },
          {
            "name": "Budget Cash Visit CY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Visit Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_Budget Cash Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_Budget Cash Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bf76c431-a041-4fc0-b9fe-e7c569b741cd"
          },
          {
            "name": "Budget Total Visit CY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_Budget Total Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_Budget Total Visits],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "lineageTag": "0481396b-562d-4b61-88e9-75ca0d80189f"
          },
          {
            "name": "$_Budget EBIDTA CY",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Budget EBIDTA],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Budget EBIDTA],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "d29e7d96-dab3-408e-aefa-dc84e0cd247d"
          },
          {
            "name": "$_Budget Net Profit CY",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Budget Net Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Budget Net Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "eebdf4ec-99c2-4600-9ee8-08d4106112bb"
          },
          {
            "name": "$_Budget Net Revenue CY",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Budget Net Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Budget Net Revenue],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "00237e38-645f-49ba-b0eb-b1185b43a53a"
          },
          {
            "name": "$_Budget Operating Profit CY",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Budget Operating Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Budget Operating Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "8e5c7bca-17fc-4aa0-a6be-13c4fbdbb503"
          },
          {
            "name": "$_Budget Gross Profit CY",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_$_Budget Gross Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_$_Budget Gross Profit],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "a1a2f22e-7c86-4dea-94a5-0f789e9dd1ef"
          },
          {
            "name": "%_Net Revenue vs YAGO",
            "displayFolder": "Comparison",
            "expression": "DIVIDE([$_Net Revenue CY]-[$_Net Revenue PY],[$_Net Revenue PY],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5e66c842-7700-4904-8a7d-2bac951db919"
          },
          {
            "name": "%_Net Revenue vs Budget",
            "displayFolder": "Comparison",
            "expression": "DIVIDE([$_Net Revenue CY]-[$_Budget Net Revenue CY],[$_Budget Net Revenue CY],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "372503d2-4768-40d5-a0f6-5e4c1c3ea1ec"
          },
          {
            "name": "A_Net Revenue vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Revenue vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Net Revenue vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "0184a751-8ff5-4b4b-aa0b-5f4818aff437"
          },
          {
            "name": "C_Net Revenue vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Revenue vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Net Revenue vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "baad31e7-5a31-46a8-ba96-6d2e9fbb1878"
          },
          {
            "name": "C_Net Revenue vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Revenue vs Budget]<0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Net Revenue vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "44a3efba-6a4d-42ef-8a40-8dffb0b24213"
          },
          {
            "name": "A_Net Revenue vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Revenue vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Net Revenue vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "a34ccda0-802b-4e66-b337-94e75a0f44b5"
          },
          {
            "name": "%_Budget Gross Profit Margin CY",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_%_Budget Gross Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Budget Gross Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cc671535-0397-4ea7-b159-21b268f7bcc6"
          },
          {
            "name": "%_Budget Net Profit Margin CY",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_%_Budget Net Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Budget Net Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c681a74c-bd00-4dbd-a986-addcfebd3a12"
          },
          {
            "name": "%_Budget EBIDTA Margin CY",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_%_Budget EBIDTA Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Budget EBIDTA Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4f9d3c7f-2634-45e0-9966-3c2f827d24cc"
          },
          {
            "name": "%_Gross Profit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE ( [$_Gross Profit CY] - [$_Gross Profit PY], [$_Gross Profit PY], 0 )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6799028a-0024-422a-87ad-204f1c028192"
          },
          {
            "name": "A_Gross Profit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Gross Profit vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Gross Profit vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "d412edf7-add9-4420-81b2-f302cf24ddf6"
          },
          {
            "name": "C_Gross Profit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Gross Profit vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Gross Profit vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "d456bda0-cb31-4ac1-b0b9-854da3c520ae"
          },
          {
            "name": "%_Gross Profit vs Budget",
            "displayFolder": "Comparison",
            "expression": "DIVIDE([$_Gross Profit CY]-[$_Budget Gross Profit CY],[$_Budget Gross Profit CY],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d050a034-e0d4-4ef1-9b9a-c9832a8c47d7"
          },
          {
            "name": "A_Gross Profit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Gross Profit vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Gross Profit vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "f18f8c11-9d35-4213-a953-5165396f1095"
          },
          {
            "name": "C_Gross Profit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Gross Profit vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Gross Profit vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "4f60f6c0-9b27-4275-9f51-1f057345f78c"
          },
          {
            "name": "%_EBIDTA vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_EBIDTA CY]-[$_EBIDTA PY],",
              "    [$_EBIDTA PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "1f78c1e0-b740-45c0-9165-453606db6e6e"
          },
          {
            "name": "%_EBIDTA vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_EBIDTA CY]-[$_Budget EBIDTA CY],",
              "    [$_Budget EBIDTA CY],",
              "    0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ab60bcf1-c136-483d-a0f6-20cdef0309a3"
          },
          {
            "name": "A_EBIDTA vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_EBIDTA vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_EBIDTA vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "7dd75ce5-3547-41a2-8043-66791d9a4361"
          },
          {
            "name": "C_EBIDTA vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_EBIDTA vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_EBIDTA vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "735eb6e3-62cc-4829-ac03-419cfc226219"
          },
          {
            "name": "A_EBIDTA vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_EBIDTA vs Budget] >0,\"\",",
              "        IF(",
              "            [%_EBIDTA vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "278c1803-d609-49b0-8741-4f2336612274"
          },
          {
            "name": "C_EBIDTA vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_EBIDTA vs Budget]<0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_EBIDTA vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "f1aa6bd0-98b7-4178-97ed-480634e29ab6"
          },
          {
            "name": "%_Net Profit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_Net Profit CY]-[$_Net Profit PY],",
              "    [$_Net Profit PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "656f2bd4-cd10-4bc7-8b57-58441555daee"
          },
          {
            "name": "%_Net Profit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_Net Profit CY]-[$_Budget Net Profit CY],",
              "    [$_Budget Net Profit CY],",
              "    0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "44234736-ad5c-467b-858a-dc972fa479f4"
          },
          {
            "name": "A_Net Profit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Profit vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Net Profit vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "955adeee-fae1-4aaf-b4b6-9ab19f92c0f2"
          },
          {
            "name": "C_Net Profit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Profit vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Net Profit vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "bf8c6b0a-bd64-48c1-9c03-3e62c1f5884d"
          },
          {
            "name": "A_Net Profit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Profit vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Net Profit vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "573d7e31-ca5e-412d-a622-104256bda84c"
          },
          {
            "name": "C_Net Profit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Profit vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Net Profit vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "0d507c51-2841-4bdf-a8c2-12d78bec2cb6"
          },
          {
            "name": "%_Gross Profit Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "",
              "   ( [%_Gross Profit Margin CY]-[%_Budget Gross Profit Margin CY])*100",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "008b25c4-8192-4d4d-987e-94903dde272a"
          },
          {
            "name": "%_Gross Profit Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "",
              "   ( [%_Gross Profit Margin CY]-[%_Gross Profit Margin PY])*100",
              ""
            ],
            "formatString": "0.00",
            "lineageTag": "3ddd8fb5-e782-4a7e-b6e6-a71af527914e"
          },
          {
            "name": "A_Gross Profit Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Gross Profit Margin vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Gross Profit Margin vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "0442dbce-efe0-44b3-99cb-5ffb8b7b9faf"
          },
          {
            "name": "C_Gross Profit Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Gross Profit Margin vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Gross Profit Margin vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "cb78f981-c08e-467a-9295-3f599198cfa8"
          },
          {
            "name": "C_Gross Profit Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Gross Profit Margin vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Gross Profit Margin vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "f691792c-5a0c-4a00-8308-77212481c7ef"
          },
          {
            "name": "A_Gross Profit Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Gross Profit Margin vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Gross Profit Margin vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "1bc6c1b9-5914-416b-bb2d-43aecd37af76"
          },
          {
            "name": "%_Cash Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Cash Visit CY]-[Cash Visit PY],",
              "    [Cash Visit PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dc69dd43-9b8c-4833-9cbf-15cb8442bc0c"
          },
          {
            "name": "A_Cash Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Visit vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Cash Visit vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "3b0f852a-0fd1-477e-a20e-2f5a6278df0a"
          },
          {
            "name": "C_Cash Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Visit vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Cash Visit vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "a860f9ef-60c4-4e70-bb67-4357badb1991"
          },
          {
            "name": "%_Cash Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Cash Visit CY]-[Budget Cash Visit CY],",
              "    [Budget Cash Visit CY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cfd538c6-134c-4fb4-a868-20a6f68323a8"
          },
          {
            "name": "A_Cash Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Visit vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Cash Visit vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "ff84c08c-41d4-48d8-b8f8-d4cfd086d2b9"
          },
          {
            "name": "C_Cash Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Visit vs Budget]<0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Cash Visit vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "eae90776-e7da-46de-8a61-c09fe98619a7"
          },
          {
            "name": "%_Credit Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Credit Visit CY]-[Credit Visit PY],",
              "    [Credit Visit PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7c0a2717-2162-4d65-8246-8ec4a39da59f"
          },
          {
            "name": "A_Credit Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Visit vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Credit Visit vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "b0b6ce1d-1354-4bd7-95e3-1adddd7b9ced"
          },
          {
            "name": "C_Credit Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Visit vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Credit Visit vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "a00c3162-039a-4071-882b-2fd3b6f85ef8"
          },
          {
            "name": "%_Credit Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Credit Visit CY]-[Budget Credit Visit CY],",
              "    [Budget Credit Visit CY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "db24ef50-7190-44c2-b924-c7c0061c35e8"
          },
          {
            "name": "A_Credit Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Visit vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Credit Visit vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "96afa4aa-3afd-48a8-baf7-8b4df81448fa"
          },
          {
            "name": "C_Credit Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Visit vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Credit Visit vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "8e075a4d-9da2-4c38-b7ab-edbc76fa1c86"
          },
          {
            "name": "%_EBIDTA Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "",
              "   ( [%_EBIDTA Margin CY]-[%_EBIDTA Margin PY])*100",
              " "
            ],
            "formatString": "0.0",
            "lineageTag": "67a2b633-77a8-42de-a26e-7607301acb16"
          },
          {
            "name": "%_EBIDTA Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "",
              "   ( [%_EBIDTA Margin CY]-[%_Budget EBIDTA Margin CY]) * 100",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "dc494592-6aec-4de7-b741-42d4e1154093"
          },
          {
            "name": "%_Cash Revenue vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_Cash Revenue Without B2B CY]-[$_Cash Revenue Without B2B PY],",
              "    [$_Cash Revenue Without B2B PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dd14dd0f-ec7c-4419-858a-806da151034a"
          },
          {
            "name": "%_Cash Revenue vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_Cash Revenue Without B2B CY]-[$_Budget Cash Revenue CY],",
              "    [$_Budget Cash Revenue CY],",
              "    0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bb3ead23-18ea-433c-8faa-f7d0f1acb54e"
          },
          {
            "name": "A_EBIDTA Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_EBIDTA Margin vs Budget] >0,\"\",",
              "        IF(",
              "            [%_EBIDTA Margin vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "7d39e338-ded3-4329-aaa2-910b08d8b36e"
          },
          {
            "name": "A_EBIDTA Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_EBIDTA Margin vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_EBIDTA Margin vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "a7b464ac-eaeb-4ffd-83ff-2a46b20d2621"
          },
          {
            "name": "C_EBIDTA Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_EBIDTA Margin vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_EBIDTA Margin vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "5d8ba404-8170-4bb4-bdb3-d147f33c0077"
          },
          {
            "name": "C_EBIDTA Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_EBIDTA Margin vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_EBIDTA Margin vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "e1d61bbe-3bba-4fc2-8e01-a3b505e6669d"
          },
          {
            "name": "A_Cash Revenue vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Revenue vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Cash Revenue vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "d83b936f-5f97-4dd0-9e2d-103ad59ac05b"
          },
          {
            "name": "A_Cash Revenue vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Revenue vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Cash Revenue vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "1c49e89d-680f-487d-8ec7-04ea4578d9fe"
          },
          {
            "name": "C_Cash Revenue vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Revenue vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Cash Revenue vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "5297e619-69b1-4713-bfe3-cf6b91651063"
          },
          {
            "name": "C_Cash Revenue vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Revenue vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Cash Revenue vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "cd8141ac-679d-4c98-bd31-f58cc713eb56"
          },
          {
            "name": "%_Credit Revenue vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_Credit Revenue CY]-[$_Credit Revenue PY],",
              "    [$_Credit Revenue PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "58358b4a-a0af-4c15-8cc5-cd48f67a1f8d"
          },
          {
            "name": "A_Credit Revenue vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Revenue vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Credit Revenue vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "6fbbafb9-4335-43f2-a5a9-d8d4630f08f2"
          },
          {
            "name": "C_Credit Revenue vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Revenue vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Credit Revenue vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "acffcb6f-e00f-41c0-a283-4de7d10b0adf"
          },
          {
            "name": "%_Credit Revenue vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_Credit Revenue CY]-[$_Budget Credit Revenue CY],",
              "    [$_Budget Credit Revenue CY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9831e944-9031-4395-878e-0478b7fd16f9"
          },
          {
            "name": "A_Credit Revenue vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Revenue vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Credit Revenue vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "39623260-3ece-431a-b980-5fac4e2b90d1"
          },
          {
            "name": "C_Credit Revenue vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Revenue vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Credit Revenue vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "88f1f5f2-7fac-49e9-a4a4-a3149e0a1529"
          },
          {
            "name": "%_Cash Revenue Per Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Cash Revenue Per Visit CY]-[Cash Revenue Per Visit PY],",
              "    [Cash Revenue Per Visit PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3b994d1c-5f36-41ac-80bb-36f947530537"
          },
          {
            "name": "%_Cash Revenue Per Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Cash Revenue Per Visit CY]-[$_Budget Cash Revenue Per Visit CY],",
              "    [$_Budget Cash Revenue Per Visit CY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0019ca2c-6f07-4bfd-a5a3-35c1e1e44fae"
          },
          {
            "name": "%_Credit Revenue Per Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Credit Revenue Per Visit CY]-[Credit Revenue Per Visit PY],",
              "    [Credit Revenue Per Visit PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2341a4fb-d860-4d7a-accb-39bb83ae04bb"
          },
          {
            "name": "%_Credit Revenue Per Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Credit Revenue Per Visit CY]-[$_Budget Credit Revenue Per Visit CY],",
              "    [$_Budget Credit Revenue Per Visit CY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "1f76df27-fc38-495c-97ff-9a20a3e32bca"
          },
          {
            "name": "A_Cash Revenue Per Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Revenue Per Visit vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Cash Revenue Per Visit vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "07962d5b-ac84-4cab-82cd-da71d20cd0de"
          },
          {
            "name": "A_Cash Revenue Per Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Revenue Per Visit vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Cash Revenue Per Visit vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "2668ace8-0c73-4032-a7e9-1e5a8f908a47"
          },
          {
            "name": "A_Credit Revenue Per Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Revenue Per Visit vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Credit Revenue Per Visit vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "1874674e-3e35-45bd-bedb-e0d8270f1308"
          },
          {
            "name": "A_Credit Revenue Per Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Revenue Per Visit vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Credit Revenue Per Visit vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "50a2b267-c424-4004-a161-2fcf0aff02f7"
          },
          {
            "name": "C_Cash Revenue Per Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Revenue Per Visit vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Cash Revenue Per Visit vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "071bb7cb-c755-444f-b16a-39fd66a9aeba"
          },
          {
            "name": "C_Cash Revenue Per Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Cash Revenue Per Visit vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Cash Revenue Per Visit vs Budget] >0, \"#479E0A\" // green",
              "            ,\"#FFAD00\" // yellow",
              "        )",
              "    )"
            ],
            "lineageTag": "37687118-9efd-492a-a9c3-e06b50ae3f35"
          },
          {
            "name": "C_Credit Revenue Per Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Revenue Per Visit vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Credit Revenue Per Visit vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "ee98d39b-973b-4ec6-b71e-16a633b9a4a8"
          },
          {
            "name": "C_Credit Revenue Per Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Credit Revenue Per Visit vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Credit Revenue Per Visit vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "5e6d3eec-cc6d-4632-8fc4-99b0f6400cfc"
          },
          {
            "name": "Comparison Net Revenue",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_$_Net Revenue] - CALCULATE([SRC_$_Net Revenue],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_$_Net Revenue],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_$_Net Revenue] - [SRC_$_Budget Net Revenue],",
              "    [SRC_$_Budget Net Revenue]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fe3617ad-37d4-433b-ac74-8134281b0bf0"
          },
          {
            "name": "SRC_$_WTNK Cash Revenue",
            "displayFolder": "WTNK Visit",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact WTNK Visit'[Amount]),",
              "    'Fact WTNK Visit'[Invoice Type] = \"Cash\"",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "c5dee15c-05a3-46ba-ace1-1a2ac64d1388"
          },
          {
            "name": "SRC_$_WTNK Credit Revenue",
            "displayFolder": "WTNK Visit",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact WTNK Visit'[Amount]),",
              "    'Fact WTNK Visit'[Invoice Type] = \"Credit\"",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "52dc1130-0215-48fb-a59a-54569d4c9248"
          },
          {
            "name": "SRC_WTNK Cash Visits",
            "displayFolder": "WTNK Visit",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact WTNK Visit'[Number of Visits]),",
              "    'Fact WTNK Visit'[Invoice Type] = \"Cash\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "90fa20a0-ebc1-482f-a794-cf53e186b488"
          },
          {
            "name": "SRC_WTNK Credit Visits",
            "displayFolder": "WTNK Visit",
            "expression": [
              "CALCULATE(",
              "    SUM('Fact WTNK Visit'[Number of Visits]),",
              "    'Fact WTNK Visit'[Invoice Type] = \"Credit\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1046f0c6-59a3-410e-ab12-b1719505ccf9"
          },
          {
            "name": "%_Net Profit Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "  (  [%_Net Profit Margin CY]-[%_Net Profit Margin PY])*100",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "2b680c6b-6451-4386-a48d-0584bb9100de"
          },
          {
            "name": "%_Net Profit Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "  (  [%_Net Profit Margin CY]-[%_Budget Net Profit Margin CY])*100",
              "  "
            ],
            "formatString": "0.0",
            "lineageTag": "70791bef-1e60-414d-bc09-cc0bfcd32c82"
          },
          {
            "name": "A_Net Profit Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Profit Margin vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Net Profit Margin vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "b345b624-69bf-4f5d-971b-0e5a9d79ec4a"
          },
          {
            "name": "A_Net Profit Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Profit Margin vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Net Profit Margin vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "87e685b3-5bc5-4975-a10e-e35540e54b6a"
          },
          {
            "name": "C_Net Profit Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Profit Margin vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Net Profit Margin vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "a5b6aea9-e111-40c4-8928-4b62eaae6760"
          },
          {
            "name": "C_Net Profit Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Net Profit Margin vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Net Profit Margin vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "be472238-c858-4f7e-b162-06043e6b2451"
          },
          {
            "name": "BenchMark_Net Revenue Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Net Revenue]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "1a546d3f-bb9b-4c0b-8e3c-9318e2967579"
          },
          {
            "name": "BenchMark_Net Revenue Best Performaing Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Net Revenue]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Net Revenue]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "c8541c39-63b1-4955-bdb7-99623e235ef9"
          },
          {
            "name": "Current YTD StartDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Date Measures",
            "expression": [
              "",
              "VAR Selected_Month = MIN('Date'[BK DATE])",
              "VAR Current_Period = MAX('Last Refresh Date'[Date Last Refreshed])",
              "RETURN",
              "IF(",
              "    ISFILTERED('Date'),",
              "    DATE(",
              "        YEAR(Selected_Month),",
              "        1,",
              "        1",
              "    ), ",
              "    DATE(",
              "        YEAR(Current_Period),",
              "        1,",
              "        1",
              "    )",
              ")"
            ],
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "e78f5452-08da-4c3b-bfa0-7cd83a19cbf4"
          },
          {
            "name": "Current YTD EndDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Date Measures",
            "expression": [
              "",
              "VAR Selected_Month = MAX('Date'[BK DATE])",
              "VAR Current_Period = MAX('Last Refresh Date'[Date Last Refreshed])",
              "RETURN ",
              "IF(",
              "    ISFILTERED('Date'),",
              "    DATE(",
              "        YEAR(Selected_Month),",
              "        MONTH(Selected_Month),",
              "        DAY(Selected_Month)",
              "    ),  ",
              "    DATE(",
              "        YEAR(Current_Period),",
              "        MONTH(Current_Period),",
              "        DAY(Current_Period)",
              "    )",
              ")"
            ],
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "706fe2a3-182a-4d4b-af67-69327057b40f"
          },
          {
            "name": "%_Budget Operating Profit Margin CY",
            "displayFolder": "Budget",
            "expression": [
              "",
              "VAR Start_Year = [Current YTD StartDate]",
              "VAR End_Year = [Current YTD EndDate]",
              "VAR Start_Month = [CurrentMonth StartDate]",
              "VAR End_Month = [CurrentMonth EndDate]",
              "",
              "VAR _YTD = ",
              "    CALCULATE([SRC_%_Budget Operating Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Year,",
              "    'Date'[BK DATE] <= End_Year",
              "    )",
              "",
              "",
              "VAR _MTD = ",
              "    CALCULATE([SRC_%_Budget Operating Profit Margin],",
              "    REMOVEFILTERS('Date'),",
              "    'Date'[BK DATE] >= Start_Month,",
              "    'Date'[BK DATE] <= End_Month",
              "    )",
              "RETURN",
              " SWITCH(",
              "       TRUE(),",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"MTD\", _MTD,",
              "         SELECTEDVALUE('MTD YTD Breakdown'[MTD YTD]) = \"YTD\", _YTD,",
              "          _YTD -- Default to YTD if no selection",
              "     )",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6fcd0ab0-7e25-49dc-9ca6-a1187e52d630"
          },
          {
            "name": "%_Operating Profit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_Operating Profit CY]-[$_Operating Profit PY],",
              "    [$_Operating Profit PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0ec5637e-cbac-48e9-85f6-0a9a3d7a4a8f"
          },
          {
            "name": "%_Operating Profit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [$_Operating Profit CY]-[$_Budget Operating Profit CY],",
              "    [$_Budget Operating Profit CY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "217b619e-52ca-4fe9-a090-bf230d2d2e04"
          },
          {
            "name": "A_Operating Profit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Operating Profit vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Operating Profit vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "f7c00345-178c-444b-b911-a4ddc743b3d9"
          },
          {
            "name": "A_Operating Profit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Operating Profit vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Operating Profit vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "3c65b10d-b079-4d10-ac85-400bc513a671"
          },
          {
            "name": "C_Operating Profit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Operating Profit vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Operating Profit vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "f2d84046-973c-4510-a685-29e2753ee9d2"
          },
          {
            "name": "C_Operating Profit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Operating Profit vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Operating Profit vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "e2da2ac0-1549-4d80-9baa-0ff4d3440ea1"
          },
          {
            "name": "BenchMark_Credit Revenue Best Performaing Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Credit Revenue]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Credit Revenue]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "f0c7f311-b3f8-40df-840b-de1e67720c2d"
          },
          {
            "name": "BenchMark_Cash Revenue Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Cash Revenue Without B2B]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "2fadf923-698f-4382-9433-0d73768002c6"
          },
          {
            "name": "BenchMark_Cash Revenue Best Performaing Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Cash Revenue Without B2B]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Cash Revenue Without B2B]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "a6eafcf4-433d-497b-bd6b-bc5d21edd008"
          },
          {
            "name": "BenchMark_Credit Revenue Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Credit Revenue]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "31a5862b-bba2-4f3b-9e6e-ef9ff4b4c205"
          },
          {
            "name": "BenchMark_Credit Visit Best Performaing Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_Credit Visits] ",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_Credit Visits]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "a480f544-43dc-432b-8320-ffa4bf621102"
          },
          {
            "name": "BenchMark_Credit Visit Best Performing Trend",
            "displayFolder": "Visit",
            "expression": [
              "",
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_Credit Visits]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4cb7bef9-1e0b-4fe3-9630-f6d8a20b997e"
          },
          {
            "name": "BenchMark_Cash Visit Best Performing Trend",
            "displayFolder": "Visit",
            "expression": [
              "",
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_Cash Visits]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "03a1384c-c9e3-404e-b1ce-886a39671bf9"
          },
          {
            "name": "BenchMark_Cash Visit Best Performaing Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_Cash Visits] ",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_Cash Visits]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "4f798ad7-9038-4875-a938-2ee2c0817586"
          },
          {
            "name": "BenchMark_Operating Profit Best Performaing Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Operating Profit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Operating Profit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "3ed294db-ca42-4bec-8d05-5e547976f0b1"
          },
          {
            "name": "BenchMark_Operating Profit Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Operating Profit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "a4a7040b-e0e3-4e22-8de6-a3d97f402a6a"
          },
          {
            "name": "BenchMark_Net Profit Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Net Profit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "d07b3428-4d1b-4b3c-bac1-1b5d083ae55d"
          },
          {
            "name": "BenchMark_Net Profit Best Performaing Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Net Profit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Net Profit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "6fcc3497-d7cb-406a-886f-e06cdbc6bfec"
          },
          {
            "name": "BenchMark_Gross Profit Best Performaing Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Gross Profit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Gross Profit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "f8639b65-5c88-472a-ab93-eaa45f7dd0bd"
          },
          {
            "name": "BenchMark_EBIDTA Best Performaing Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_EBIDTA]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_EBIDTA]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "f9b8f83e-eae3-4781-85a1-727aaa1b7b96"
          },
          {
            "name": "BenchMark_EBIDTA Margin Best Performaing Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_EBIDTA Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_EBIDTA Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "0508fbb6-a49b-4fa7-8082-1d018910c060"
          },
          {
            "name": "BenchMark_Gross Profit Margin Best Performaing Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_Gross Profit Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_Gross Profit Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "055aeb4f-7e96-4ef2-b596-e6d18d7238f1"
          },
          {
            "name": "BenchMark_Net Profit Margin Best Performaing Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_Net Profit Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_Net Profit Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "ca90026b-a0c6-4ab7-9912-1a5db3ba3437"
          },
          {
            "name": "BenchMark_Operating Profit Margin Best Performaing Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_Operating Profit Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_Operating Profit Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))",
              ""
            ],
            "lineageTag": "96f0464b-f967-4ae1-a149-32c75407042e"
          },
          {
            "name": "BenchMark_Gross Profit Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Gross Profit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "66305fe1-7a81-4a97-94cc-d024e662adb7"
          },
          {
            "name": "BenchMark_EBIDTA Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_EBIDTA]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "23eadb78-28cf-4b8c-9651-4a0d8b019d22"
          },
          {
            "name": "BenchMark_Net Profit Margin Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_Net Profit Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "c3f62f7f-863f-4f4f-a95a-eb833ec07be8"
          },
          {
            "name": "BenchMark_Gross Profit Margin Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_Gross Profit Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "91d1e645-8d51-420e-9a8b-6a5067635934"
          },
          {
            "name": "BenchMark_Operating Profit Margin Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_Operating Profit Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "334236f7-da77-4aa3-9b80-63c90e2b27da"
          },
          {
            "name": "BenchMark_Cash Revenue Per Visit Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Cash Revenue Per Visit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "7855e401-2f9a-46c2-9896-3bd39ea3ccd9"
          },
          {
            "name": "BenchMark_Credit Revenue Per Visit Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Credit Revenue Per Visit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "25c3fc5b-fba6-42f2-a588-699773637b74"
          },
          {
            "name": "BenchMark_Credit Revenue Per Visit Best Performaing Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Credit Revenue Per Visit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Credit Revenue Per Visit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "b22f0bd3-424a-4e15-8be8-973a2a621d16"
          },
          {
            "name": "BenchMark_Cash Revenue Per Visit Best Performaing Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Cash Revenue Per Visit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_$_Cash Revenue Per Visit]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "89f84392-6074-4783-95d1-12f32363177a"
          },
          {
            "name": "BenchMark_Avg Cash Revenue Trend",
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Cash Revenue Without B2B]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3a1d875f-3bec-4b3b-bbc1-500ac832ceb6"
          },
          {
            "name": "BenchMark_Avg Credit Revenue Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Credit Revenue]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "4dd523e1-2950-4a19-891d-58c68d60bcef"
          },
          {
            "name": "BenchMark_Avg Net Revenue Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Net Revenue]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "f0c376a8-5e34-4d41-a19f-95d97d7dc19c"
          },
          {
            "name": "BenchMark_Avg Credit Revenue Per Visit Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Credit Revenue Per Visit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "be695352-5c65-4e63-a22c-59b20ba4bba4"
          },
          {
            "name": "BenchMark_Avg Cash Revenue Per Visit Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Cash Revenue Per Visit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "551e718d-9b78-4567-a914-16b43818c385"
          },
          {
            "name": "BenchMark_Avg Credit Visit Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_Credit Visits]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "14cc9363-43ac-43e4-a2f7-bc7e23dfcf8f"
          },
          {
            "name": "BenchMark_Avg Cash Visit Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_Cash Visits]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "9d6c4fe2-96f5-4a24-a284-632ecc164eb1"
          },
          {
            "name": "BenchMark_Avg Net Profit Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Net Profit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "86cacc33-9d8e-445a-9b80-20ceec25d943"
          },
          {
            "name": "BenchMark_Avg Gross Profit Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Gross Profit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "64aa4b5f-4459-480d-82f6-76d2ab592915"
          },
          {
            "name": "BenchMark_Avg Operating Profit Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Operating Profit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "a92e132a-44b1-4a4e-9ef9-4e9e0031eca1"
          },
          {
            "name": "BenchMark_Avg EBIDTA Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_EBIDTA]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "a1d5e271-87f7-4e90-bd16-acfe40eb395e"
          },
          {
            "name": "BenchMark_Avg Net Profit Margin Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_%_Net Profit Margin]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "7f64cab5-ad35-422f-bc3d-8322ac5b4a57"
          },
          {
            "name": "BenchMark_Avg Gross Profit Margin Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_%_Gross Profit Margin]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "dbe9fa2d-3630-4228-9ada-b9f5e5b5a1a6"
          },
          {
            "name": "BenchMark_Avg Operating Profit Margin Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_%_Operating Profit Margin]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "c689d5c6-b50a-40bb-aac8-2da9fd443a63"
          },
          {
            "name": "BenchMark_Avg EBIDTA Margin Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_%_EBIDTA Margin]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "aff858bd-8718-4af3-94ee-8a4e1e2a7ee2"
          },
          {
            "name": "Previous Month EndDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Date Measures",
            "expression": [
              "",
              "VAR Selected_Month = MAX('Date'[BK DATE])",
              "VAR Current_Period = MAX('Last Refresh Date'[Date Last Refreshed])",
              "RETURN",
              "     if (",
              "        ISFILTERED('Date'),",
              "        DATE(",
              "        YEAR(Selected_Month)-1,",
              "        MONTH(Selected_Month),",
              "        day(Selected_Month)",
              "        )",
              "        ,",
              "",
              "         DATE(",
              "            YEAR(Current_Period)-1,",
              "            MONTH(Current_Period),",
              "            day(Current_Period)",
              "        )",
              "        )"
            ],
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "05b34531-6f6f-4342-bdb2-a4fc9953de92"
          },
          {
            "name": "Previous Month StartDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Date Measures",
            "expression": [
              "",
              "VAR Selected_Month = MIN('Date'[BK DATE])",
              "VAR Current_Period = MAX('Last Refresh Date'[Date Last Refreshed])",
              "RETURN",
              "    if (",
              "        ISFILTERED('Date'),",
              "        DATE(",
              "            YEAR(Selected_Month)-1,",
              "            MONTH(Selected_Month),",
              "            01",
              "        )",
              "        ,",
              "        DATE(",
              "            YEAR(Current_Period)-1,",
              "            MONTH(Current_Period),",
              "            01",
              "        )",
              ")",
              ""
            ],
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "877fdd12-be2e-41ef-ac66-3de9e65f2114"
          },
          {
            "name": "BenchMark_EBIDTA Margin Best Performing Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Voucher",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_%_EBIDTA Margin]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "20bd22c3-db37-46bc-9447-aba4c8431fc3"
          },
          {
            "name": "%_Operating Profit Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              " ([%_Operating Profit Margin CY] - [%_Operating Profit Margin PY])*100",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "5997052f-7241-4a0e-ad9d-120807ce3747"
          },
          {
            "name": "%_Operating Profit Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "( [%_Operating Profit Margin CY] - [%_Budget Operating Profit Margin CY])*100",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "dd8e1d47-1c69-4930-bc5d-5fd2a8715d84"
          },
          {
            "name": "A_Operating Profit Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Operating Profit Margin vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Operating Profit Margin vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "ce229bb9-6c31-445a-b6c7-51dd40a5ee46"
          },
          {
            "name": "A_Operating Profit Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Operating Profit Margin vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Operating Profit Margin vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "e313c073-2e1c-45c7-96f7-287ca17d87c7"
          },
          {
            "name": "C_Operating Profit Margin vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Operating Profit Margin vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Operating Profit Margin vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "15d3efc2-896d-4ed2-825c-81e93a7f1f4a"
          },
          {
            "name": "C_Operating Profit Margin vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Operating Profit Margin vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Operating Profit Margin vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "961a6ef3-398d-40c3-9a6e-4aa24f242aa4"
          },
          {
            "name": "Comparison Gross Profit",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_$_Gross Profit] - CALCULATE([SRC_$_Gross Profit],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_$_Gross Profit],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_$_Gross Profit] - [SRC_$_Budget Gross Profit],",
              "    [SRC_$_Budget Gross Profit]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "10571fbf-52f7-4e27-94d1-bf06a32f9ea8"
          },
          {
            "name": "Comparison EBIDTA",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_$_EBIDTA] - CALCULATE([SRC_$_EBIDTA],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_$_EBIDTA],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_$_EBIDTA] - [SRC_$_Budget EBIDTA],",
              "    [SRC_$_Budget EBIDTA]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "28a8282a-1244-4294-9304-0e17633bff5c"
          },
          {
            "name": "Comparison Operating Profit",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_$_Operating Profit] - CALCULATE([SRC_$_Operating Profit],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_$_Operating Profit],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_$_Operating Profit] - [SRC_$_Budget Operating Profit],",
              "    [SRC_$_Budget Operating Profit]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1274171f-c088-4b6f-8e5b-ef0936dc6fb1"
          },
          {
            "name": "Comparison Net Profit",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_$_Net Profit] - CALCULATE([SRC_$_Net Profit],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_$_Net Profit],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_$_Net Profit] - [SRC_$_Budget Net Profit],",
              "    [SRC_$_Budget Net Profit]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9b9bc95c-fb1f-4f31-8b74-22f8ba3cc07d"
          },
          {
            "name": "Comparison Credit Revenue",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_$_Credit Revenue] - CALCULATE([SRC_$_Credit Revenue],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_$_Credit Revenue],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_$_Credit Revenue] - [SRC_$_Budget Credit Revenue],",
              "    [SRC_$_Budget Credit Revenue]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c9450a80-968c-4736-8319-5f5b66a22eab"
          },
          {
            "name": "Comparison Cash Revenue",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_$_Cash Revenue Without B2B] - CALCULATE([SRC_$_Cash Revenue Without B2B],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_$_Cash Revenue Without B2B],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_$_Cash Revenue Without B2B] - [SRC_$_Budget Cash Revenue],",
              "    [SRC_$_Budget Cash Revenue]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "64a8c733-c27c-4104-947c-c6a882ded53e"
          },
          {
            "name": "Comparison Cash Revenue Per Visit",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_$_Cash Revenue Per Visit] - CALCULATE([SRC_$_Cash Revenue Per Visit],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_$_Cash Revenue Per Visit],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_$_Cash Revenue Per Visit] - [SRC_$_Budget Cash Revenue Per Visit],",
              "    [SRC_$_Budget Cash Revenue Per Visit]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "259bdd0e-9c02-45a8-a09c-ee07aef294c9"
          },
          {
            "name": "Comparison Credit Revenue Per Visit",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_$_Credit Revenue Per Visit] - CALCULATE([SRC_$_Credit Revenue Per Visit],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_$_Credit Revenue Per Visit],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_$_Credit Revenue Per Visit] - [SRC_$_Budget Credit Revenue Per Visit],",
              "    [SRC_$_Budget Credit Revenue Per Visit]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6b1b57e6-e06a-4619-b088-8e0bace62094"
          },
          {
            "name": "Comparison Cash Visit",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_Cash Visits] - CALCULATE([SRC_Cash Visits],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_Cash Visits],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_Cash Visits] - [SRC_Budget Cash Visits],",
              "    [SRC_Budget Cash Visits]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "51857701-639b-48cd-8476-2dab9012b0e6"
          },
          {
            "name": "Comparison Credit Visit",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_Credit Visits] - CALCULATE([SRC_Credit Visits],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_Credit Visits],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_Credit Visits] - [SRC_Budget Credit Visits],",
              "    [SRC_Budget Credit Visits]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "93279035-3088-4dcc-bea5-4413978e6d9f"
          },
          {
            "name": "Comparison Total Visit",
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "DIVIDE(",
              "    [SRC_Total Visits] - CALCULATE([SRC_Total Visits],SAMEPERIODLASTYEAR('Date'[BK DATE])),",
              "    CALCULATE([SRC_Total Visits],SAMEPERIODLASTYEAR('Date'[BK DATE]))",
              ")",
              "VAR vs_Budget = ",
              "DIVIDE(",
              "    [SRC_Total Visits] - [SRC_Budget Total Visits],",
              "    [SRC_Budget Total Visits]",
              ")",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "554520e8-2e11-47fd-9f06-6cf740095149"
          },
          {
            "name": "Comparison Gross Profit Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "",
              "    ( [SRC_%_Gross Profit Margin] - CALCULATE([SRC_%_Gross Profit Margin],SAMEPERIODLASTYEAR('Date'[BK DATE])) )*100",
              "",
              "VAR vs_Budget = ",
              "",
              "    ([SRC_%_Gross Profit Margin] - [SRC_%_Budget Gross Profit Margin])*100",
              "",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              "",
              ""
            ],
            "lineageTag": "aa280902-0999-4635-9b8e-6254e499add8"
          },
          {
            "name": "Comparison Operating Profit Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "",
              "    ( [SRC_%_Operating Profit Margin] - CALCULATE([SRC_%_Operating Profit Margin],SAMEPERIODLASTYEAR('Date'[BK DATE])) )*100",
              "",
              "VAR vs_Budget = ",
              "",
              "    ([SRC_%_Operating Profit Margin] - [SRC_%_Budget Operating Profit Margin])*100",
              "",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              "",
              "",
              ""
            ],
            "lineageTag": "561c1467-ee88-4a54-88d7-2dc232b880be"
          },
          {
            "name": "Comparison Net Profit Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "",
              "    ( [SRC_%_Net Profit Margin] - CALCULATE([SRC_%_Net Profit Margin],SAMEPERIODLASTYEAR('Date'[BK DATE])) )*100",
              "",
              "VAR vs_Budget = ",
              "",
              "    ([SRC_%_Net Profit Margin] - [SRC_%_Budget Net Profit Margin])*100",
              "",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              "",
              "",
              "    ",
              ""
            ],
            "lineageTag": "ae2bad07-2c88-4e29-8103-7cb547e3f2ca"
          },
          {
            "name": "Comparison EBIDTA Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Table Comparison",
            "expression": [
              "",
              "VAR vs_YAGO = ",
              "",
              "    ( [SRC_%_EBIDTA Margin] - CALCULATE([SRC_%_EBIDTA Margin],SAMEPERIODLASTYEAR('Date'[BK DATE])) )*100",
              "",
              "VAR vs_Budget = ",
              "",
              "    ([SRC_%_EBIDTA Margin] - [SRC_%_Budget EBIDTA Margin])*100",
              "",
              "",
              "RETURN",
              "    SWITCH(",
              "        SELECTEDVALUE(ComparisonTable[Comparison]),",
              "        \"vs. YAGO\", vs_YAGO,",
              "        \"vs. Budget\", vs_Budget,",
              "        BLANK()",
              "    )",
              "    ",
              ""
            ],
            "lineageTag": "29926a14-3ba4-463b-8520-ee9e083e5198"
          },
          {
            "name": "%_Total Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Visit CY]-[Total Visit PY],",
              "    [Total Visit PY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0190b341-86cf-4be7-b914-5654e0c4c759"
          },
          {
            "name": "%_Total Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Visit CY]-[Budget Total Visit CY],",
              "    [Budget Total Visit CY],",
              "0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "fe8bfe37-966f-4600-82cc-8c48a4dad048"
          },
          {
            "name": "A_Total Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Total Visit vs YAGO] >0,\"\",",
              "        IF(",
              "            [%_Total Visit vs YAGO]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "e473f68e-f47e-40ac-8755-6977c93ac155"
          },
          {
            "name": "A_Total Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Total Visit vs Budget] >0,\"\",",
              "        IF(",
              "            [%_Total Visit vs Budget]<0,\"\",\"-\"",
              "        )",
              "    )"
            ],
            "lineageTag": "c417766f-60b0-4ac1-acd8-dff670f40c9b"
          },
          {
            "name": "C_Total Visit vs YAGO",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Total Visit vs YAGO] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Total Visit vs YAGO] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "9743400f-7af8-48c9-b6ff-1ea093d0c98e"
          },
          {
            "name": "C_Total Visit vs Budget",
            "displayFolder": "Comparison",
            "expression": [
              "",
              "    IF(",
              "        [%_Total Visit vs Budget] <0,\"#F5303D\" //red",
              "        ,",
              "        IF(",
              "            [%_Total Visit vs Budget] >0, \"#479E0A\",\"#FFAD00\"",
              "        )",
              "    )"
            ],
            "lineageTag": "250d7a79-726a-4b7e-84db-209f083e1105"
          },
          {
            "name": "BenchMark_Avg Total Visit Trend",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_Total Visits]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Company Average\",_AVG,",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "3051dc12-6f05-4f49-b484-43750be723b1"
          },
          {
            "name": "BenchMark_Total Visit Best Performing Trend",
            "displayFolder": "Visit",
            "expression": [
              "",
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_Total Visits]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN ",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE('Benchmarks Breakdown'[Value4])=\"Best Performed Facility\",MaxValue,",
              "    BLANK()",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b8f7f796-2d5e-4fc3-b853-2aface3a8d71"
          },
          {
            "name": "BenchMark_Total Visit Best Performaing Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR MaxValue = ",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_Total Visits] ",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK()",
              "        ), [Value]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "Var MaxName =",
              "CALCULATE(",
              "    MAXX(",
              "        FILTER(",
              "            SUMMARIZE(",
              "                'Dim Business Line',",
              "                'Dim Business Line'[Sub Business Line Dashboard Name],",
              "                \"Value\", [SRC_Total Visits]",
              "            ),",
              "            'Dim Business Line'[Sub Business Line Dashboard Name] <> BLANK() && ",
              "            [Value] = MaxValue",
              "        ),[Sub Business Line Dashboard Name]",
              "    ),REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "",
              "RETURN ",
              "    CONCATENATE( MaxName , CONCATENATE(\": \", FORMAT(MaxValue, \"#,##0\")))"
            ],
            "lineageTag": "e7e9d7e4-c3bb-4dee-b1c4-01099c945845"
          },
          {
            "name": "BenchMark_Avg Net Revenue Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Net Revenue]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "380f36f7-c5ea-4b5c-86aa-a464c6db2c68"
          },
          {
            "name": "BenchMark_Avg Credit Visit Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "VAR _AVG=",
              "    CALCULATE(",
              "        AVERAGEX('Dim Business Line',[SRC_Credit Visits]",
              "        ),",
              "        REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              "    )",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "1a56fc9b-0661-4140-b4c5-2966d1f508ee"
          },
          {
            "name": "BenchMark_Avg Credit Revenue Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Credit Revenue]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "40d1f171-0946-4a1e-bf80-bbe180bf5492"
          },
          {
            "name": "BenchMark_Avg Total Visit Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_Total Visits]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "65a7b029-3055-4fa8-bfd2-dc68b6c36f64"
          },
          {
            "name": "BenchMark_Avg Credit Revenue Per Visit Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Credit Revenue Per Visit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "da0ad7e0-4f12-4c1d-834d-13b45e8e804e"
          },
          {
            "name": "BenchMark_Avg Cash Visit Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_Cash Visits]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "7df29bfa-b8aa-418f-bdb7-e400fd095ac4"
          },
          {
            "name": "BenchMark_Avg Cash Revenue Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Cash Revenue Without B2B]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "448ca097-f5f6-4979-9685-40395ef3fd96"
          },
          {
            "name": "BenchMark_Avg Cash Revenue Per Visit Tooltip",
            "displayFolder": "Visit",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Cash Revenue Per Visit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "68084aa8-a4b3-4ea3-8433-74ebb86b6dac"
          },
          {
            "name": "BenchMark_Avg Operating Profit Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Operating Profit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "df3757ee-3831-4b18-865c-919d790a4657"
          },
          {
            "name": "BenchMark_Avg Operating Profit Margin Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_%_Operating Profit Margin]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "fdfaeff9-085c-48d8-99f6-16b2d01a0a46"
          },
          {
            "name": "BenchMark_Avg Net Profit Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Net Profit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "0ab72026-ded4-4f17-b1fd-102d0399a6c2"
          },
          {
            "name": "BenchMark_Avg Net Profit Margin Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_%_Net Profit Margin]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "3cc9239b-1060-48c6-9952-abf8f0d0d6f2"
          },
          {
            "name": "BenchMark_Avg Gross Profit Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_Gross Profit]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "d523e48c-d73a-4fef-9848-b633270b231f"
          },
          {
            "name": "BenchMark_Avg Gross Profit Margin Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_%_Gross Profit Margin]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "b86abe45-de11-4b4c-8c5f-1749a30c40c6"
          },
          {
            "name": "BenchMark_Avg EBIDTA Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_$_EBIDTA]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")",
              ""
            ],
            "lineageTag": "d3a557d2-ab31-4150-a382-ac2f0b71ddd4"
          },
          {
            "name": "BenchMark_Avg EBIDTA Margin Tooltip",
            "displayFolder": "Voucher",
            "expression": [
              "",
              "var _AVG = CALCULATE(",
              "    AVERAGEX('Dim Business Line',[SRC_%_EBIDTA Margin]",
              "    ),",
              "    REMOVEFILTERS('Dim Business Line'[Sub Business Line Dashboard Name])",
              ")",
              "RETURN",
              "FORMAT(_AVG, \"#,##0\")"
            ],
            "lineageTag": "63e574ac-c6d6-40b8-b981-7fec88a587fc"
          },
          {
            "name": "Has Data",
            "displayFolder": "Date Measures",
            "expression": [
              "",
              "IF(",
              "    COUNTROWS('Fact Budget') > 0 ||",
              "    COUNTROWS('Fact Visit Budget') > 0 ||",
              "    COUNTROWS('Fact Visit') > 0 ||",
              "    COUNTROWS('Fact Voucher') > 0 ||",
              "    COUNTROWS('Fact WTNK Visit') > 0,",
              "    1,",
              "    0",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "cef7de86-8875-496f-8f8d-5bf85d588554"
          }
        ],
        "partitions": [
          {
            "name": "Calculations",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Business Line",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PK Business Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2c562e5-2d83-4ce4-b600-9d39bbd6ed86",
            "sourceColumn": "PK Business Line",
            "summarizeBy": "none"
          },
          {
            "name": "Business Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb8030e9-ad35-494d-aa25-cd80ac1007b7",
            "sourceColumn": "Business Line",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Business Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1024bf29-fd98-4e2f-ae89-3cf4ec560ef9",
            "sourceColumn": "Sub Business Line",
            "summarizeBy": "none"
          },
          {
            "name": "Facility Clinic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27c47599-0818-4fe0-a336-7ae92bcfb098",
            "sourceColumn": "Facility Clinic",
            "summarizeBy": "none"
          },
          {
            "name": "IS Facility",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9f636e31-2e54-4282-8ca8-72a3e8e4646e",
            "sourceColumn": "IS Facility",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Business Line Dashboard Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b204d02e-b47a-4a65-a918-12c416bcf691",
            "sourceColumn": "Sub Business Line Dashboard Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e548c7da-f75f-43b1-8ff8-c864ceb63f49",
        "partitions": [
          {
            "name": "Dim Business Line",
            "mode": "import",
            "queryGroup": "Dim Tables",
            "source": {
              "expression": [
                "let",
                "     Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_d_business_line_View = gold_Schema{[Name=\"vw_d_business_line\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_d_business_line_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Visit",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Transaction ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ee1af1b-83a8-4718-ad79-380bf5b76feb",
            "sourceColumn": "Transaction ID",
            "summarizeBy": "none"
          },
          {
            "name": "Patient ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2811aa00-443c-4965-8597-7d1528aed2b3",
            "sourceColumn": "Patient ID",
            "summarizeBy": "none"
          },
          {
            "name": "Legal Entity ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e640f21d-2456-4249-b393-261255484f95",
            "sourceColumn": "Legal Entity ID",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8883a419-ce9b-472a-aea6-570486b06c05",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Payer Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6379071e-4772-45e5-b760-c8bbc76b5c7b",
            "sourceColumn": "Payer Type",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "11c6d99d-d3b5-47b8-a309-0a5f2d30a5cf",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Is Visit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "31c49fec-390a-442b-b557-409fe945241d",
            "sourceColumn": "Is Visit",
            "summarizeBy": "none"
          },
          {
            "name": "Is Cash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "28874a66-5ecd-4277-8b3d-4995b820e349",
            "sourceColumn": "Is Cash",
            "summarizeBy": "none"
          },
          {
            "name": "Rejection Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed0eb811-abe9-4605-9ef4-e35a24116a1d",
            "sourceColumn": "Rejection Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "FK Facility",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "10650ce3-4f2f-4c10-8117-0114b1152c49",
            "sourceColumn": "FK Facility",
            "summarizeBy": "none"
          },
          {
            "name": "FK Doctor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d51a76e6-1c36-4e0f-907d-c7646999ea88",
            "sourceColumn": "FK Doctor",
            "summarizeBy": "none"
          },
          {
            "name": "FK Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c17e274a-a8ef-4d66-9d39-e92da285ae17",
            "sourceColumn": "FK Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "FK Customer Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "655f8597-d609-43a9-8a47-127f08da98db",
            "sourceColumn": "FK Customer Account",
            "summarizeBy": "none"
          },
          {
            "name": "FK Service Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5dab1773-9b99-4553-bb26-12b702382572",
            "sourceColumn": "FK Service Category",
            "summarizeBy": "none"
          },
          {
            "name": "FK DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6c0068d-2a7b-4c41-8972-d710c0e377d4",
            "sourceColumn": "FK DATE",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00dd35bb-a790-4fd5-80d9-7f5298e87787",
            "sourceColumn": "Customer Group",
            "summarizeBy": "none"
          },
          {
            "name": "FK Business Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ddf01f2e-9f92-489f-b3a2-e66fe03bc7f5",
            "sourceColumn": "FK Business Line",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4981960e-41d1-4336-99ec-7235621bef60",
        "partitions": [
          {
            "name": "Fact Visit",
            "mode": "import",
            "queryGroup": "Fact Tables",
            "source": {
              "expression": [
                "let",
                "    Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "         ",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_f_visit_View = gold_Schema{[Name=\"vw_f_visit\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_f_visit_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Visit Budget",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Cash Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0f3db9b-e9ab-47fa-94b7-65522ddd85c0",
            "sourceColumn": "Cash Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Cash Visits Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6e9a32d8-f8e5-4df2-82bd-c4958a2eec24",
            "sourceColumn": "Cash Visits Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Credit Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e6c3453a-4cc2-40fd-8cb9-7f29622dbddc",
            "sourceColumn": "Net Credit Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Credit Visits Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f63a67ac-0318-4602-92fa-50aa180f334d",
            "sourceColumn": "Credit Visits Number",
            "summarizeBy": "sum"
          },
          {
            "name": "FK Doctor ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e16871d2-f334-44ea-9ed8-f6adb83e23cb",
            "sourceColumn": "FK Doctor ID",
            "summarizeBy": "none"
          },
          {
            "name": "FK Facility",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f036e2a-9e34-4c33-9a12-6a19e9478827",
            "sourceColumn": "FK Facility",
            "summarizeBy": "none"
          },
          {
            "name": "FK Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0231be24-5460-41b2-819f-069ef02add97",
            "sourceColumn": "FK Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "Fk Business Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8bc037a8-b370-4860-aac7-30df52407ef9",
            "sourceColumn": "Fk Business Line",
            "summarizeBy": "none"
          },
          {
            "name": "FK DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9ead5efd-7ee4-4923-b257-4976e7ac718f",
            "sourceColumn": "FK DATE",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ce70a1e7-76d9-436a-b8a1-e68dd139e375",
        "partitions": [
          {
            "name": "Fact Visit Budget",
            "mode": "import",
            "queryGroup": "Fact Tables",
            "source": {
              "expression": [
                "let",
                "    Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "         ",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_f_visitbudget_View = gold_Schema{[Name=\"vw_f_visitbudget\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_f_visitbudget_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact Budget",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Journal Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "248c9114-dc76-440f-8c3a-e0f73d51eb69",
            "sourceColumn": "Journal Account ID",
            "summarizeBy": "count"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d51da10-fcca-4b5c-b75c-e853ad4b101d",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Allocated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9a723c46-d685-4947-83a7-e02547e05fdd",
            "sourceColumn": "Allocated",
            "summarizeBy": "none"
          },
          {
            "name": "Agreement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77fff4b7-829e-4fdf-b715-49b14bfade26",
            "sourceColumn": "Agreement",
            "summarizeBy": "none"
          },
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b605e8ef-f05b-40f8-bca5-9f9a6fdd30c0",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "L1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab0b375b-fe4f-4d47-882a-f11e9f9c5062",
            "sourceColumn": "L1",
            "summarizeBy": "none"
          },
          {
            "name": "L2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41923187-a047-4be5-8af9-0a6f456b50e9",
            "sourceColumn": "L2",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d52821f2-2962-49cb-987d-3fd6222fe3dc",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Fk Doctor ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d285d38f-d54a-4f8f-801d-f3fb9b25b999",
            "sourceColumn": "Fk Doctor ID",
            "summarizeBy": "none"
          },
          {
            "name": "Fk Business Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bd35bc3e-6f3b-434b-b071-b72268fde241",
            "sourceColumn": "Fk Business Line",
            "summarizeBy": "none"
          },
          {
            "name": "Fk Facility",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d83bfe0b-7bdb-4f09-8fb9-1a454f7cd405",
            "sourceColumn": "Fk Facility",
            "summarizeBy": "none"
          },
          {
            "name": "Fk Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db275b0e-2bed-49e5-ad57-faa2a33cd8ad",
            "sourceColumn": "Fk Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "Fk Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c348eca6-63c2-4871-8adc-4c206be8fd0d",
            "sourceColumn": "Fk Date",
            "summarizeBy": "none"
          },
          {
            "name": "Amount Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "731036c8-a735-4c40-89be-31399a22c001",
            "sourceColumn": "Amount Flag",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c18133bb-1a99-447e-b69d-45dd2c91cef2",
        "partitions": [
          {
            "name": "Fact Budget",
            "mode": "import",
            "queryGroup": "Fact Tables",
            "source": {
              "expression": [
                "let",
                "    Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "         ",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_f_budget_View = gold_Schema{[Name=\"vw_f_budget\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_f_budget_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ComparisonTable",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8dec68e513604b5c9d96629b805a6db4"
          }
        ],
        "columns": [
          {
            "name": "Comparison",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c6e0ac03-5ec5-4fbb-b818-a552bd6edc7c",
            "sourceColumn": "[Comparison]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "014537ac-9b42-46c5-8c2a-bf01f36775c2",
        "partitions": [
          {
            "name": "ComparisonTable",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"Comparison\", STRING, ",
                "    {",
                "        {\"vs. YAGO\"},",
                "        {\"vs. Budget\"}",
                "    }",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Fact WTNK Visit",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FK DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a901de3-6cbe-4a13-bee0-772cfcd64bb6",
            "sourceColumn": "FK DATE",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f460b44-c4ee-4e63-9a6b-e1122e54944c",
            "sourceColumn": "Invoice Type",
            "summarizeBy": "none"
          },
          {
            "name": "FK Facility",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90b8fcb0-b92d-4de2-b4a4-fed53a7056d2",
            "sourceColumn": "FK Facility",
            "summarizeBy": "none"
          },
          {
            "name": "FK Doctor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b6bf6a37-7d16-4b81-8100-ef9e230139da",
            "sourceColumn": "FK Doctor",
            "summarizeBy": "none"
          },
          {
            "name": "FK Specialty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9610e3a-93ac-49d2-854b-6a3e0198ccc1",
            "sourceColumn": "FK Specialty",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "61ff9506-d924-406c-ad70-dd3097386277",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of Visits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9c79ae29-5e7c-484e-ab73-8ad67889b0f6",
            "sourceColumn": "Number of Visits",
            "summarizeBy": "sum"
          },
          {
            "name": "FK Business Line",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa545a95-cda8-4194-8669-22a0983bcde7",
            "sourceColumn": "FK Business Line",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5bc31f54-b5db-4b0b-8003-5e4d3307783a",
        "partitions": [
          {
            "name": "Fact WTNK Visit",
            "mode": "import",
            "queryGroup": "Fact Tables",
            "source": {
              "expression": [
                "let",
                "    Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "         ",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_f_wtnkvisit_View = gold_Schema{[Name=\"vw_f_wtnkvisit\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_f_wtnkvisit_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim Customer Account",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1372a78a-6ea1-4f53-bcbd-9e43a386411c",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "PK Customer Account",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3cde463f-1141-4058-8723-de0d83f0fe17",
            "sourceColumn": "PK Customer Account",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dc3b0e20-65db-47c3-b01d-c4ef2b1c0a90",
        "partitions": [
          {
            "name": "Dim Customer Account",
            "mode": "import",
            "queryGroup": "Dim Tables",
            "source": {
              "expression": [
                "let",
                "    Source = ",
                "        if #\"Environment Name\" = \"development\" then",
                "            Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"Production\" then",
                "            Databricks.Catalogs(PRD_CON, PRD_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else if #\"Environment Name\" = \"qa\" then",
                "            Databricks.Catalogs(QA_CON, QA_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null])",
                "        else ",
                "         Databricks.Catalogs(DEV_CON, DEV_CATALOG, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "         ",
                "    _Database = Source{[Name=#\"Environment Name\",Kind=\"Database\"]}[Data],",
                "    gold_Schema = _Database{[Name=\"gold\",Kind=\"Schema\"]}[Data],",
                "    vw_d_customeraccount_View = gold_Schema{[Name=\"vw_d_customeraccount\",Kind=\"View\"]}[Data]",
                "in",
                "    vw_d_customeraccount_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Trend Comparative Breakdown",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "10331daca4a042639510189612b3a183"
          }
        ],
        "columns": [
          {
            "name": "Trend Comparative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "4cc69ce7-7107-4cb7-9e37-be7590fa2a32",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "breakdow Fields"
                }
              ]
            },
            "sortByColumn": "breakdow Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "breakdow Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "1324c54e-50b1-45b9-8e21-da663248685c",
            "sortByColumn": "breakdow Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "breakdow Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "d8db9a2c-1e14-4097-97ac-665ac7eec1bf",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3e28bfbe-b07d-484c-8fcb-a5ec61697bd1",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2fca3f3c-e0e6-4fb0-8a74-73294ae5e6ef",
        "partitions": [
          {
            "name": "Trend Comparative Breakdown",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Comparative\", NAMEOF('Dim Business Line'[Sub Business Line Dashboard Name]), 0, \"Comparative\"),",
                "    (\"YEAR\", NAMEOF('Date'[YEAR NR]), 1, \"Trend\"),",
                "    (\"MONTH\", NAMEOF('Date'[MONTH SHORT NAME]), 2, \"Trend\"),",
                "    (\"DAY\", NAMEOF('Date'[MONTH DAY NR]), 3, \"Trend\")",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "MTD YTD Breakdown",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bdd9a119236f41688d79c8399c0bf2e0"
          }
        ],
        "columns": [
          {
            "name": "MTD YTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "570868f4-f622-4807-a337-7e537da3e0cf",
            "sourceColumn": "[Date Filter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "9e821017-3428-48f2-b569-121cb57f9e78",
        "partitions": [
          {
            "name": "MTD YTD Breakdown",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"Date Filter\", STRING, ",
                "    {",
                "        {\"MTD\"},",
                "        {\"YTD\"}",
                "    }",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Benchmarks Breakdown",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c637c60e25684e64babc755dd8e2dfdf"
          }
        ],
        "columns": [
          {
            "name": "Benchmarks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "899cc05b-94cc-4932-8d00-ad81a3bdb534",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Benchmarks Fields"
                }
              ]
            },
            "sortByColumn": "Benchmarks Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Benchmarks Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "b0a094e6-7774-4f1f-a15d-841877c61f41",
            "sortByColumn": "Benchmarks Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Benchmarks Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "51121992-30de-4079-bf45-4a22cb412f3d",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Value4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cd568b5c-53a6-4ee4-b9b3-5e74a4afd3b0",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6c130bab-3036-48e4-b2a7-f54f3255dca5",
        "partitions": [
          {
            "name": "Benchmarks Breakdown",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Avg Cash Revenue Per Visit\", NAMEOF('Calculations'[BenchMark_Avg Cash Revenue Per Visit Trend]), 0,\"Company Average\"),",
                "    (\"Avg Cash Revenue\", NAMEOF('Calculations'[BenchMark_Avg Cash Revenue Trend]), 1,\"Company Average\"),",
                "    (\"Avg Cash Visit\", NAMEOF('Calculations'[BenchMark_Avg Cash Visit Trend]), 2,\"Company Average\"),",
                "    (\"Avg Credit Revenue Per Visit\", NAMEOF('Calculations'[BenchMark_Avg Credit Revenue Per Visit Trend]), 3,\"Company Average\"),",
                "    (\"Avg Credit Revenue\", NAMEOF('Calculations'[BenchMark_Avg Credit Revenue Trend]), 4,\"Company Average\"),",
                "    (\"Avg Credit Visit\", NAMEOF('Calculations'[BenchMark_Avg Credit Visit Trend]), 5,\"Company Average\"),",
                "    (\"Avg Net Revenue\", NAMEOF('Calculations'[BenchMark_Avg Net Revenue Trend]), 6,\"Company Average\"),",
                "    (\"Best Performing Cash Revenue\", NAMEOF('Calculations'[BenchMark_Cash Revenue Best Performing Trend]), 7,\"Best Performed Facility\"),",
                "    (\"Best Performing Cash Revenue Per Visit\", NAMEOF('Calculations'[BenchMark_Cash Revenue Per Visit Best Performing Trend]), 8,\"Best Performed Facility\"),",
                "    (\"Best Performing Cash Visit\", NAMEOF('Calculations'[BenchMark_Cash Visit Best Performing Trend]), 9,\"Best Performed Facility\"),",
                "    (\"Best Performing Credit Revenue\", NAMEOF('Calculations'[BenchMark_Credit Revenue Best Performing Trend]), 10,\"Best Performed Facility\"),",
                "    (\"Best Performing Credit Revenue Per Visit\", NAMEOF('Calculations'[BenchMark_Credit Revenue Per Visit Best Performing Trend]), 11,\"Best Performed Facility\"),",
                "    (\"Best Performing Credit Visit\", NAMEOF('Calculations'[BenchMark_Credit Visit Best Performing Trend]), 12,\"Best Performed Facility\"),",
                "    (\"Best Performing Net Revenue\", NAMEOF('Calculations'[BenchMark_Net Revenue Best Performing Trend]), 13,\"Best Performed Facility\"),",
                "    (\"Avg EBIDTA Margin\", NAMEOF('Calculations'[BenchMark_Avg EBIDTA Margin Trend]), 14,\"Company Average\"),",
                "    (\"Avg EBIDTA\", NAMEOF('Calculations'[BenchMark_Avg EBIDTA Trend]), 15,\"Company Average\"),",
                "    (\"Avg Gross Profit Margin\", NAMEOF('Calculations'[BenchMark_Avg Gross Profit Margin Trend]), 16,\"Company Average\"),",
                "    (\"Avg Gross Profit\", NAMEOF('Calculations'[BenchMark_Avg Gross Profit Trend]), 17,\"Company Average\"),",
                "    (\"Avg Net Profit Margin\", NAMEOF('Calculations'[BenchMark_Avg Net Profit Margin Trend]), 18,\"Company Average\"),",
                "    (\"Avg Net Profit\", NAMEOF('Calculations'[BenchMark_Avg Net Profit Trend]), 19,\"Company Average\"),",
                "    (\"Avg Operating Profit Margin\", NAMEOF('Calculations'[BenchMark_Avg Operating Profit Margin Trend]), 20,\"Company Average\"),",
                "    (\"Avg Operating Profit\", NAMEOF('Calculations'[BenchMark_Avg Operating Profit Trend]), 21,\"Company Average\"),",
                "    (\"Best Performaing EBIDTA\", NAMEOF('Calculations'[BenchMark_EBIDTA Best Performing Trend]), 22,\"Best Performed Facility\"),",
                "    (\"Best Performaing Gross Profit\", NAMEOF('Calculations'[BenchMark_Gross Profit Best Performing Trend]), 23,\"Best Performed Facility\"),",
                "    (\"Best Performaing Gross Profit Margin\", NAMEOF('Calculations'[BenchMark_Gross Profit Margin Best Performing Trend]), 24,\"Best Performed Facility\"),",
                "    (\"Best Performaing Net Profit\", NAMEOF('Calculations'[BenchMark_Net Profit Best Performing Trend]), 25,\"Best Performed Facility\"),",
                "    (\"Best Performaing Net Profit Margin\", NAMEOF('Calculations'[BenchMark_Net Profit Margin Best Performing Trend]), 26,\"Best Performed Facility\"),",
                "    (\"Best Performaing Operating Profit\", NAMEOF('Calculations'[BenchMark_Operating Profit Best Performing Trend]), 27,\"Best Performed Facility\"),",
                "    (\"Best Performaing Operating Profit Margin\", NAMEOF('Calculations'[BenchMark_Operating Profit Margin Best Performing Trend]), 28,\"Best Performed Facility\"),",
                "    (\"Best Performaing EBIDTA Margin\", NAMEOF('Calculations'[BenchMark_EBIDTA Margin Best Performing Trend]), 29,\"Best Performed Facility\"),",
                "    (\"Best Performaing Total Visit\", NAMEOF('Calculations'[BenchMark_Total Visit Best Performing Trend]), 30,\"Best Performed Facility\"),",
                "    (\"Avg Total Visit\", NAMEOF('Calculations'[BenchMark_Avg Total Visit Trend]), 31,\"Company Average\"),",
                "    (\"No Selection for BenchMark\", \"\", 32,\"Not Selected\")",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}