table Sheet1
	lineageTag: 55378d76-626a-4ae1-9be5-039e68d4186f

	column InoviceYear
		dataType: string
		lineageTag: 6f82567b-cceb-45ee-9e0b-f308aa330a79
		summarizeBy: none
		sourceColumn: InoviceYear

		annotation SummarizationSetBy = Automatic

	column InvoiceMonth
		dataType: string
		lineageTag: 9aaeef02-4aac-4edf-924b-964c05ab6eb6
		summarizeBy: none
		sourceColumn: InvoiceMonth

		annotation SummarizationSetBy = Automatic

	column InvoiceDayOn
		dataType: int64
		formatString: 0
		lineageTag: fd51c4dd-ab4e-4c2a-bd35-3cfa1d3c8ed7
		summarizeBy: sum
		sourceColumn: InvoiceDayOn

		annotation SummarizationSetBy = Automatic

	column PolyclinicName
		dataType: string
		lineageTag: 49e9dae0-870c-42f2-9a65-38e0e4c5105d
		summarizeBy: none
		sourceColumn: PolyclinicName

		annotation SummarizationSetBy = Automatic

	column DoctorNumber
		dataType: int64
		formatString: 0
		lineageTag: f6bd9232-5e6c-4ee0-b766-310432be441f
		summarizeBy: sum
		sourceColumn: DoctorNumber

		annotation SummarizationSetBy = Automatic

	column DoctorName
		dataType: string
		lineageTag: 9bb0474e-e4e1-4939-8c1c-ad541c557aa9
		summarizeBy: none
		sourceColumn: DoctorName

		annotation SummarizationSetBy = Automatic

	column ClinicName
		dataType: string
		lineageTag: 8eea6df3-433d-405e-9a92-787199f871e8
		summarizeBy: none
		sourceColumn: ClinicName

		annotation SummarizationSetBy = Automatic

	column CashRevenue
		dataType: double
		lineageTag: 7723a04d-e438-4469-bbe6-6095898d1c48
		summarizeBy: sum
		sourceColumn: CashRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CashPatientNumber
		dataType: double
		lineageTag: f811e01b-fdaa-49cc-8538-1ddc9e59a748
		summarizeBy: sum
		sourceColumn: CashPatientNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CreditRevenue
		dataType: double
		lineageTag: 437361b9-c8df-4d01-99ac-74186ca6c928
		summarizeBy: sum
		sourceColumn: CreditRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Credit PatientNumber'
		dataType: double
		lineageTag: c4b72958-8fed-4a3f-b284-3d3cb1c2093c
		summarizeBy: sum
		sourceColumn: Credit PatientNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalRevenue
		dataType: double
		lineageTag: f759ff15-2dcc-4759-a3d4-af10cd791898
		summarizeBy: sum
		sourceColumn: TotalRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalPatientNumber
		dataType: double
		lineageTag: f5a6841f-a7e1-47c3-8f33-0972b02d7d40
		summarizeBy: sum
		sourceColumn: TotalPatientNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BusinessUnite
		dataType: string
		lineageTag: 159a33ea-5532-4478-889d-62aa2aabb498
		summarizeBy: none
		sourceColumn: BusinessUnite

		annotation SummarizationSetBy = Automatic

	column WD
		dataType: string
		lineageTag: e52d5a93-6206-4d8b-aeae-1c4a3aa618bb
		summarizeBy: none
		sourceColumn: WD

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\OsamaAfifi\Downloads\TeamRevenueBudget.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"InoviceYear", type text}, {"InvoiceMonth", type text}, {"InvoiceDayOn", Int64.Type}, {"PolyclinicName", type text}, {"DoctorNumber", Int64.Type}, {"DoctorName", type text}, {"ClinicName", type text}, {"CashRevenue", type number}, {"CashPatientNumber", type number}, {"CreditRevenue", type number}, {"Credit PatientNumber", type number}, {"TotalRevenue", type number}, {"TotalPatientNumber", type number}, {"BusinessUnite", type text}, {"WD", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

